function bool = includesTrials(masterMetadataTable, trialInfoList)
    %%INCLUDESTRIALS Check if trials from trialInfoList are included in masterMetadataTable
    %   This function assumes the typical folder structure generated by EthoVision
    %
    %   Inputs:
    %       masterMetadataTable - A table containing metadata about all trials, loaded via io.metadata.loadMasterMetadata()
    %       trialInfoList - A struct array containing trial information, obtained from io.ethovision.filterTrials()
    %
    %   Outputs:
    %       bool - A logical array indicating whether each trial in trialInfoList is included in masterMetadataTable
    %
    %   See also: io.metadata.loadMasterMetadata, io.ethovision.filterTrials

    arguments
        masterMetadataTable table
        trialInfoList (:, 1) struct
    end

    [isValidTable, missingHeaders] = io.metadata.isMasterMetadataTable(masterMetadataTable);
    if ~isValidTable
        error('The provided masterMetadataTable is missing required headers: %s', strjoin(missingHeaders, ', '));
    end

    bool = false(size(trialInfoList));

    % The Ethovision Media folder is in: */<ExperimentName>/Media Files/<TrialName>.<ext>
    trialMediaFiles = {trialInfoList.media};
    [folder, ~, ~] = cellfun(@fileparts, trialMediaFiles, 'UniformOutput', false);
    [folder, ~, ~] = cellfun(@fileparts, folder, 'UniformOutput', false);
    [~, experimentNames, ~] = cellfun(@fileparts, folder, 'UniformOutput', false);
    
    % For each trial, experimentName and trialInfoList.trialNumeric
    % must match a row somewhere in masterMetadataTable, both ETHOVISION_FILE and ETHOVISION_TRIAL, respectively
    for i = 1:length(trialInfoList)
        matchesExperiment = strcmp(masterMetadataTable.ETHOVISION_FILE, experimentNames{i});
        if ~isempty(trialInfoList(i).trialNumeric) && isnumeric(trialInfoList(i).trialNumeric)
            matchesTrialNumeric = masterMetadataTable.ETHOVISION_TRIAL == trialInfoList(i).trialNumeric;
        else
            matchesTrialNumeric = false(height(masterMetadataTable), 1);
        end
        bool(i) = any(matchesExperiment & matchesTrialNumeric);
    end
end