function [bool, missingHeaders] = isMasterMetadataTable(x)
    arguments
        x table
    end
    
    requiredHeaders = { ...
        'EXPERIMENT_DATE', 'SOURCE_CODE', 'CAGE_CODE', 'ANIMAL_ID', ...
        'ANIMAL_DOB', 'ANIMAL_P_AGE', 'ANIMAL_SEX', 'ANIMAL_STRAIN', ...
        'ANIMAL_GENOTYPE', 'ETHOVISION_FILE', 'ETHOVISION_TRIAL', ...
        'STIMULUS_PROTOCOL', 'HABITUATION_DURATION_SEC', 'SPEAKER_FLIPPED', ...
        'STIM_START_FRAME'
    };
    bool = all(ismember(requiredHeaders, x.Properties.VariableNames));
    missingHeaders = setdiff(requiredHeaders, x.Properties.VariableNames);
end