function updateBatchDataTree(appTreeRootNode, batchData, kvargs)
%%UPDATEBATCHDATATREE Update the app's batch data tree based on the provided batchData
%   This function performs differential updates to add/remove only changed experiments and trials
%
%   Inputs:
%       appTreeRootNode - The root node of the app's tree (matlab.ui.container.TreeNode)
%       batchData - A struct array of trialInfo, generated by ui.trackingPlatforms.TrackingProvider.filterTrials()
%
%   Name-Value Pair Arguments:
%       'MetadataTable' - The master metadata table loaded from an Excel file with io.metadata.loadMasterMetadata, only required if you want to filter trials based on metadata
%       'Filters' - A struct of filters to apply when loading trials, only required if you want to filter trials based on specific criteria
%
%   See also: io.ethovision.filterTrials

arguments
    appTreeRootNode matlab.ui.container.TreeNode
    batchData struct

    kvargs.MetadataTable {validator.mustBeFileTableOrEmpty} = table()
    kvargs.Filters (:,1) {mustBeValidFiltersOrEmpty} = struct('sex', {cell(0)}, 'strain', {cell(0)}, 'genotype', {cell(0)})
    kvargs.TrackingProvider {validator.mustBeTrackingProviderOrEmpty} = []
end

if isempty(kvargs.Filters)
    kvargs.Filters = struct('sex', {cell(0)}, 'strain', {cell(0)}, 'genotype', {cell(0)});
else
    % Assert as cellstr for easier comparison later
    filterFields = fieldnames(kvargs.Filters);
    for i = 1:length(filterFields)
        if isempty(kvargs.Filters.(filterFields{i}))
            continue; % No filter for this field
        end
        fieldValue = kvargs.Filters.(filterFields{i});
        kvargs.Filters.(filterFields{i}) = cellstr(fieldValue);
    end
end

masterMetadata = table();
if istable(kvargs.MetadataTable)
    [bool, missingHeaders] = io.metadata.isMasterMetadataTable(kvargs.MetadataTable);
    if ~bool
        error('The provided MasterMetadataTable does not contain a valid master metadata table. Missing headers: {'' %s ''}', strjoin(missingHeaders, ''', '''));
    end
    masterMetadata = kvargs.MetadataTable;
elseif ~isempty(kvargs.MetadataTable)
    masterMetadata = io.metadata.loadMasterMetadata(kvargs.MetadataTable);
end

if ~isempty(masterMetadata) && ~isempty(kvargs.TrackingProvider)
    doFilter = true;
    sex = unique(masterMetadata.("ANIMAL_SEX"));
    sex = sex(~cellfun(@isempty, sex));

    strains = unique(masterMetadata.("ANIMAL_STRAIN"));
    strains = strains(~cellfun(@isempty, strains));

    genotypes = unique(masterMetadata.("ANIMAL_GENOTYPE"));
    genotypes = genotypes(~cellfun(@isempty, genotypes));

    % If any filter field is empty, set to all possible values
    if isempty(kvargs.Filters.sex) || all(cellfun(@isempty, kvargs.Filters.sex))
        kvargs.Filters.sex = sex(:)';
    end
    if isempty(kvargs.Filters.strain) || all(cellfun(@isempty, kvargs.Filters.strain))
        kvargs.Filters.strain = strains(:)';
    end
    if isempty(kvargs.Filters.genotype) || all(cellfun(@isempty, kvargs.Filters.genotype))
        kvargs.Filters.genotype = genotypes(:)';
    end
else
    doFilter = false;
end



% Filter MasterMetadata based on provided filters, create a whitelist of valid experiment project dirs + trial numbers
whitelist = struct('experiment', '', 'arena', '', 'trial', []); % Fields: experiment = ETHOVISION_FILE; arena = ETHOVISION_ARENA; trial = ETHOVISION_TRIAL
if doFilter
    % Apply filters
    filteredRows = masterMetadata;
    filteredRows = filteredRows(ismember(filteredRows.("ANIMAL_SEX"), kvargs.Filters.sex), :);
    filteredRows = filteredRows(ismember(filteredRows.("ANIMAL_STRAIN"), kvargs.Filters.strain), :);
    filteredRows = filteredRows(ismember(filteredRows.("ANIMAL_GENOTYPE"), kvargs.Filters.genotype), :);
    % Build whitelist
    if ~isempty(filteredRows)
        projects = unique(filteredRows.("ETHOVISION_FILE"), 'stable');
        projects = projects(~cellfun(@isempty, projects));
        for i = 1:length(projects)
            proj = projects{i};
            projRows = filteredRows(strcmp(filteredRows.("ETHOVISION_FILE"), proj), :);

            arenas = unique(projRows.("ETHOVISION_ARENA"), 'stable');
            arenas = arenas(~cellfun(@isempty, arenas));
            for j = 1:length(arenas)
                arena = arenas{j};
                arenaRows = projRows(strcmp(projRows.("ETHOVISION_ARENA"), arena), :);
                trials = unique(arenaRows.("ETHOVISION_TRIAL"), 'stable');
                % Ignore if trials are not numeric (should not happen, best to define this as a data validation step in the Excel sheet as well)
                if ~isnumeric(trials)
                    trials = trials(cellfun(@(x) isnumeric(x) || (ischar(x) && all(isstrprop(x, 'digit'))), trials));
                    trials = cellfun(@(x) str2double(x), trials);
                end
                trials = trials(~arrayfun(@isempty, trials));
                if isempty(trials)
                    continue;
                end
                whitelist(end+1) = struct('experiment', proj, 'arena', arena, 'trial', trials); %#ok<AGROW>
            end
        end
    end
end
% Remove the initial empty struct
whitelist = whitelist(2:end);


% Handle empty or invalid batchData
if isempty(batchData) || ~isfield(batchData, 'dir')
    % Remove all existing nodes if batchData is empty/invalid
    nodes = appTreeRootNode.Children;
    delete(nodes);
    return;
end

batchDataDirs = batchData.dir;
newExperiments = {batchDataDirs.name};
newExpPaths = fullfile({batchDataDirs.folder}, newExperiments);

% Get current experiment nodes
currentExpNodes = appTreeRootNode.Children;

% Handle case where Children returns empty or placeholder objects
if isempty(currentExpNodes) || ~isa(currentExpNodes(1), 'matlab.ui.container.TreeNode')
    currentExpNames = {};
else
    currentExpNames = {currentExpNodes.Text};
end

% Get tree reference for checking nodes
tree = [];
try
    tree = ancestor(appTreeRootNode, 'matlab.ui.container.CheckBoxTree');
    if ~isempty(tree)
        % Clean up invalid nodes from CheckedNodes to prevent issues
        tree.CheckedNodes = tree.CheckedNodes(isvalid(tree.CheckedNodes));
    end
catch
end

% Find experiments to remove (exist in tree but not in new data)
experimentsToRemove = setdiff(currentExpNames, newExperiments);
for i = 1:length(experimentsToRemove)
    nodeToRemove = findNodeByText(currentExpNodes, experimentsToRemove{i});
    if ~isempty(nodeToRemove)
        delete(nodeToRemove);
    end
end

% Process each experiment in the new data
for i = 1:length(newExperiments)
    exp = newExperiments{i};
    expPath = newExpPaths{i};

    % Find existing experiment node
    currentExpNodes = appTreeRootNode.Children; % Refresh after deletions
    expNode = findNodeByText(currentExpNodes, exp);

    if isempty(expNode)
        % Add new experiment node
        expNode = uitreenode(appTreeRootNode, 'Text', exp, 'NodeData', expPath);

        % Auto-check if parent (root) is checked
        if ~isempty(tree) && ismember(appTreeRootNode, tree.CheckedNodes)
            tree.CheckedNodes = [tree.CheckedNodes; expNode];
        end

        hasValidTrials = updateTrialsForExperiment(expNode, expPath, whitelist, doFilter, tree);
        % Remove experiment node if it has no valid trials
        if ~hasValidTrials
            delete(expNode);
        end
    else
        % Update existing experiment node's trials
        hasValidTrials = updateTrialsForExperiment(expNode, expPath, whitelist, doFilter, tree);
        % Remove experiment node if it has no valid trials
        if ~hasValidTrials
            delete(expNode);
        end
    end
end

% Reorder experiment nodes if filtering is active
if doFilter
    orderedExps = unique({whitelist.experiment}, 'stable');
    % Reverse the order of experiments
    orderedExps = orderedExps(end:-1:1);

    currentExpNodes = appTreeRootNode.Children;
    if ~isempty(currentExpNodes)
        [~, idx] = ismember({currentExpNodes.Text}, orderedExps);
        % Filter out nodes that might not be in whitelist (shouldn't happen if logic is correct, but safe)
        validIdx = idx > 0;
        if any(validIdx)
            % Sort based on index in orderedExps
            nodesToSort = currentExpNodes(validIdx);
            idx = idx(validIdx);
            [~, sortIdx] = sort(idx);
            appTreeRootNode.Children = nodesToSort(sortIdx);
        end
    end
end

expand(appTreeRootNode);

end

function node = findNodeByText(nodes, text)
%%FINDNODEBYTEXT Find a node with matching text in an array of nodes
node = [];

% Handle empty or invalid node arrays
if isempty(nodes) || ~isa(nodes(1), 'matlab.ui.container.TreeNode')
    return;
end

for i = 1:length(nodes)
    if isvalid(nodes(i)) && strcmp(nodes(i).Text, text)
        node = nodes(i);
        return;
    end
end
end

function hasValidTrials = updateTrialsForExperiment(expNode, expPath, whitelist, doFilter, tree)
%%UPDATETRIALSFOREXPERIMENT Update trials for a specific experiment node
%   Returns true if the experiment has valid trials, false otherwise

if nargin < 5
    tree = [];
end

try
    [newTrialNames, newTrialInfo] = io.ethovision.filterTrials(expPath);
    % Filter out trials that are multi-arena exports
    singleArenaIdx = arrayfun(@(t) isfield(t, 'multipleArena') && ~t.multipleArena, newTrialInfo);
    newTrialNames = newTrialNames(singleArenaIdx);
    newTrialInfo = newTrialInfo(singleArenaIdx);

    % Apply whitelist filter if required
    if doFilter
        validIndices = false(size(newTrialNames));
        experimentName = expNode.Text;

        % Whitelist for this experiment
        expWhitelist = whitelist(strcmp({whitelist.experiment}, experimentName));

        if ~isempty(expWhitelist)
            for j = 1:length(newTrialNames)
                trialInfo = newTrialInfo(j);
                % Check if this trial is in expWhitelist
                % Match arena and trial number

                for k = 1:length(expWhitelist)
                    if strcmp(expWhitelist(k).arena, trialInfo.arena) && ismember(trialInfo.trialNumeric, expWhitelist(k).trial)
                        validIndices(j) = true;
                        break;
                    end
                end
            end
        end

        newTrialNames = newTrialNames(validIndices);
        newTrialInfo = newTrialInfo(validIndices);
    end

    % Check if any valid trials remain after filtering
    if isempty(newTrialNames)
        % Remove all existing trial nodes and return false
        currentTrialNodes = expNode.Children;
        delete(currentTrialNodes);
        hasValidTrials = false;
        return;
    end

catch
    % If filterTrials fails, remove all trials for this experiment
    currentTrialNodes = expNode.Children;
    delete(currentTrialNodes);
    hasValidTrials = false;
    return;
end

% Get current trial nodes
currentTrialNodes = expNode.Children;

% Handle case where Children returns empty or placeholder objects
if isempty(currentTrialNodes) || ~isa(currentTrialNodes(1), 'matlab.ui.container.TreeNode')
    currentTrialNames = {};
else
    currentTrialNames = {currentTrialNodes.Text};
end

% Find trials to remove
trialsToRemove = setdiff(currentTrialNames, newTrialNames);
for i = 1:length(trialsToRemove)
    nodeToRemove = findNodeByText(currentTrialNodes, trialsToRemove{i});
    if ~isempty(nodeToRemove)
        delete(nodeToRemove);
    end
end


% Find trials to add
trialsToAdd = setdiff(newTrialNames, currentTrialNames);

nodesToCheck = matlab.ui.container.TreeNode.empty;

% Add new trial nodes
for i = 1:length(trialsToAdd)
    trialName = trialsToAdd{i};
    % Find the corresponding trial info
    trialIdx = strcmp(newTrialNames, trialName);
    if any(trialIdx)
        trialInfo = newTrialInfo(trialIdx);
        tNode = uitreenode(expNode, 'Text', trialName, 'NodeData', trialInfo);
        if ~isempty(tree)
            nodesToCheck(end+1) = tNode;
        end
    end
end

if ~isempty(tree)
    % Clean up invalid nodes
    currentChecked = tree.CheckedNodes;
    if ~isempty(currentChecked)
        currentChecked = currentChecked(isvalid(currentChecked));
        tree.CheckedNodes = currentChecked;
    end
    
    if ismember(expNode, currentChecked)
        % Parent is checked, ensure all children are checked
        children = expNode.Children;
        if ~isempty(children)
            missing = children(~ismember(children, currentChecked));
            if ~isempty(missing)
                tree.CheckedNodes = [currentChecked; missing];
            end
        end
    end
end

% Update existing trial nodes (in case NodeData changed)
currentTrialNodes = expNode.Children; % Refresh after changes
if ~isempty(currentTrialNodes) && isa(currentTrialNodes(1), 'matlab.ui.container.TreeNode')
    for i = 1:length(currentTrialNodes)
        trialName = currentTrialNodes(i).Text;
        trialIdx = strcmp(newTrialNames, trialName);
        if any(trialIdx)
            newTrialInfoForNode = newTrialInfo(trialIdx);
            % Update NodeData if it has changed
            if ~isequal(currentTrialNodes(i).NodeData, newTrialInfoForNode)
                currentTrialNodes(i).NodeData = newTrialInfoForNode;
            end
        end
    end
end

% If we reach here, there are valid trials
hasValidTrials = true;

% Reorder trial nodes if filtering is active
if doFilter && ~isempty(whitelist)
    currentTrialNodes = expNode.Children;
    if ~isempty(currentTrialNodes)
        orderedChildren = matlab.ui.container.TreeNode.empty;
        allNodeData = [currentTrialNodes.NodeData];

        % Get whitelist for this experiment again
        experimentName = expNode.Text;
        expWhitelist = whitelist(strcmp({whitelist.experiment}, experimentName));

        for k = 1:length(expWhitelist)
            arena = expWhitelist(k).arena;
            trials = expWhitelist(k).trial;
            for t = 1:length(trials)
                tNum = trials(t);
                % Find matching node
                matchIdx = find(strcmp({allNodeData.arena}, arena) & [allNodeData.trialNumeric] == tNum);
                if ~isempty(matchIdx)
                    orderedChildren(end+1) = currentTrialNodes(matchIdx);
                end
            end
        end

        if ~isempty(orderedChildren)
            expNode.Children = orderedChildren;
        end
    end
end
end




function mustBeValidFiltersOrEmpty(x)
%%MUSTBEVALIDFILTERSOREMPTY Validate that input is a valid filters struct or empty
if isempty(x)
    return;
end
requiredFields = {'sex', 'strain', 'genotype'};
if ~isstruct(x) || ~all(isfield(x, requiredFields))
    error('Filters must be a struct with fields: {''%s''}. To specify no filter for certain fields, set their values to {} empty cell.', strjoin(requiredFields, ''', '''));
end
% All filters must be text
for i = 1:length(requiredFields)
    fieldValue = x.(requiredFields{i});
    if ~isempty(fieldValue) && ~ischar(fieldValue) && ~iscellstr(fieldValue) && ~isstring(fieldValue)
        error('Filter field ''%s'' must be a character vector, a string array, cell array of strings, or empty. To specify no filter for certain fields, set their values to {cell(0)} empty cell.', requiredFields{i});
    end
end
end