function updateBatchDataTree(appTreeRootNode, batchData)
    %%UPDATEBATCHDATATREE Update the app's batch data tree based on the provided batchData
    %   This function performs differential updates to add/remove only changed experiments and trials
    %
    %   Inputs:
    %       appTreeRootNode - The root node of the app's tree (matlab.ui.container.TreeNode)
    %       batchData - A struct array of trialInfo, generated by io.ethovision.filterTrials()
    %   See also: io.ethovision.filterTrials

    arguments
        appTreeRootNode matlab.ui.container.TreeNode
        batchData struct
    end

    % Handle empty or invalid batchData
    if isempty(batchData) || ~isfield(batchData, 'dir')
        % Remove all existing nodes if batchData is empty/invalid
        nodes = appTreeRootNode.Children;
        delete(nodes);
        return;
    end

    batchDataDirs = batchData.dir;
    newExperiments = {batchDataDirs.name};
    newExpPaths = fullfile({batchDataDirs.folder}, newExperiments);

    % Get current experiment nodes
    currentExpNodes = appTreeRootNode.Children;
    
    % Handle case where Children returns empty or placeholder objects
    if isempty(currentExpNodes) || ~isa(currentExpNodes(1), 'matlab.ui.container.TreeNode')
        currentExpNames = {};
    else
        currentExpNames = {currentExpNodes.Text};
    end
    
    % Find experiments to remove (exist in tree but not in new data)
    experimentsToRemove = setdiff(currentExpNames, newExperiments);
    for i = 1:length(experimentsToRemove)
        nodeToRemove = findNodeByText(currentExpNodes, experimentsToRemove{i});
        if ~isempty(nodeToRemove)
            delete(nodeToRemove);
        end
    end
    
    % Process each experiment in the new data
    for i = 1:length(newExperiments)
        exp = newExperiments{i};
        expPath = newExpPaths{i};
        
        % Find existing experiment node
        currentExpNodes = appTreeRootNode.Children; % Refresh after deletions
        expNode = findNodeByText(currentExpNodes, exp);
        
        if isempty(expNode)
            % Add new experiment node
            expNode = uitreenode(appTreeRootNode, 'Text', exp, 'NodeData', expPath);
            hasValidTrials = updateTrialsForExperiment(expNode, expPath);
            % Remove experiment node if it has no valid trials
            if ~hasValidTrials
                delete(expNode);
            end
        else
            % Update existing experiment node's trials
            hasValidTrials = updateTrialsForExperiment(expNode, expPath);
            % Remove experiment node if it has no valid trials
            if ~hasValidTrials
                delete(expNode);
            end
        end
    end

    expand(appTreeRootNode);
end

function node = findNodeByText(nodes, text)
    %%FINDNODEBYTEXT Find a node with matching text in an array of nodes
    node = [];
    
    % Handle empty or invalid node arrays
    if isempty(nodes) || ~isa(nodes(1), 'matlab.ui.container.TreeNode')
        return;
    end
    
    for i = 1:length(nodes)
        if strcmp(nodes(i).Text, text)
            node = nodes(i);
            return;
        end
    end
end

function hasValidTrials = updateTrialsForExperiment(expNode, expPath)
    %%UPDATETRIALSFOREXPERIMENT Update trials for a specific experiment node
    %   Returns true if the experiment has valid trials, false otherwise
    
    try
        [newTrialNames, newTrialInfo] = io.ethovision.filterTrials(expPath);
        % Filter out trials that are multi-arena exports
        singleArenaIdx = arrayfun(@(t) isfield(t, 'multipleArena') && ~t.multipleArena, newTrialInfo);
        newTrialNames = newTrialNames(singleArenaIdx);
        newTrialInfo = newTrialInfo(singleArenaIdx);
        
        % Check if any valid trials remain after filtering
        if isempty(newTrialNames)
            % Remove all existing trial nodes and return false
            currentTrialNodes = expNode.Children;
            delete(currentTrialNodes);
            hasValidTrials = false;
            return;
        end
        
    catch
        % If filterTrials fails, remove all trials for this experiment
        currentTrialNodes = expNode.Children;
        delete(currentTrialNodes);
        hasValidTrials = false;
        return;
    end
    
    % Get current trial nodes
    currentTrialNodes = expNode.Children;
    
    % Handle case where Children returns empty or placeholder objects
    if isempty(currentTrialNodes) || ~isa(currentTrialNodes(1), 'matlab.ui.container.TreeNode')
        currentTrialNames = {};
    else
        currentTrialNames = {currentTrialNodes.Text};
    end
    
    % Find trials to remove
    trialsToRemove = setdiff(currentTrialNames, newTrialNames);
    for i = 1:length(trialsToRemove)
        nodeToRemove = findNodeByText(currentTrialNodes, trialsToRemove{i});
        if ~isempty(nodeToRemove)
            delete(nodeToRemove);
        end
    end

    
    % Find trials to add
    trialsToAdd = setdiff(newTrialNames, currentTrialNames);
    
    % Add new trial nodes
    for i = 1:length(trialsToAdd)
        trialName = trialsToAdd{i};
        % Find the corresponding trial info
        trialIdx = strcmp(newTrialNames, trialName);
        if any(trialIdx)
            trialInfo = newTrialInfo(trialIdx);
            uitreenode(expNode, 'Text', trialName, 'NodeData', trialInfo);
        end
    end
    
    % Update existing trial nodes (in case NodeData changed)
    currentTrialNodes = expNode.Children; % Refresh after changes
    if ~isempty(currentTrialNodes) && isa(currentTrialNodes(1), 'matlab.ui.container.TreeNode')
        for i = 1:length(currentTrialNodes)
            trialName = currentTrialNodes(i).Text;
            trialIdx = strcmp(newTrialNames, trialName);
            if any(trialIdx)
                newTrialInfoForNode = newTrialInfo(trialIdx);
                % Update NodeData if it has changed
                if ~isequal(currentTrialNodes(i).NodeData, newTrialInfoForNode)
                    currentTrialNodes(i).NodeData = newTrialInfoForNode;
                end
            end
        end
    end
    
    % If we reach here, there are valid trials
    hasValidTrials = true;
end