function normalizedTable = normalizeSummaryTable(summaryTable)
    %%NORMALIZESUMMARYTABLE Normalizes the summary table by:
    %   1. Calculate the percentage of Matched Frames over Original Frames for each stimulus and speaker position.
    %   2. Group the trials by Animal UID and Stimulus Task,
    %       If a single animal has multiple trials with the same stimulus task,
    %       average the values for that animal for that stimulus task.
    %
    %   normalizedTable = population.stats.normalizeSummaryTable(summaryTable)
    %
    %   Inputs:
    %       summaryTable - A table generated by population.stats.populationSummary
    %
    %   Outputs:
    %       normalizedTable - A table with normalized values, each row is a unique animal (Animal UID) doing a specific stimulus task (Stimulus Task)
    %
    %   See also: population.stats.populationSummary

    arguments
        summaryTable table
    end

    requiredColumns = {'Strain', 'Sex', 'Genotype', 'Age', 'Cage Code', 'Animal ID', 'Animal UID', 'Stimulus Task'};
    missing = setdiff(requiredColumns, summaryTable.Properties.VariableNames, 'stable');
    if ~isempty(missing)
        error('The provided summaryTable is missing required columns: { ''%s'' }', strjoin(missing, ''', '''));
    end


    %% Create a normalized data columns (for each stim) that divides by total frame in "All Left Speaker" or "All Right Speaker"
    % Norm Matched Speakers
    normMatchedLeft = zeros(height(summaryTable), 1);
    normMatchedRight = zeros(height(summaryTable), 1);

    for i = 1:height(summaryTable)
        normMatchedLeft(i) = summaryTable{i, "Matched Left Speaker"} / summaryTable{i, "All Left Speaker"};
        normMatchedRight(i) = summaryTable{i, "Matched Right Speaker"} / summaryTable{i, "All Right Speaker"};
    end
    summaryTable = addvars(summaryTable, normMatchedLeft, normMatchedRight, 'NewVariableNames', ["Norm Matched Left Speaker", "Norm Matched Right Speaker"]);


    % For each row, use the value in "Matched Left Speaker" and find the other column that has the same value, Normalize that column by / "All Left Speaker"
    % Same for "Matched Right Speaker"
    for i = 1:height(summaryTable)
        matchedLeftValue = summaryTable{i, "Matched Left Speaker"};
        matchedRightValue = summaryTable{i, "Matched Right Speaker"};

        % Find the column name that has the same value as matchedLeftValue
        leftColName = "";
        rightColName = "";
        for j = 1:width(summaryTable)
            if isnumeric(summaryTable{i, j}) && summaryTable{i, j} == matchedLeftValue && summaryTable.Properties.VariableNames{j} ~= "Matched Left Speaker"
                leftColName = summaryTable.Properties.VariableNames{j};
            end
            if isnumeric(summaryTable{i, j}) && summaryTable{i, j} == matchedRightValue && summaryTable.Properties.VariableNames{j} ~= "Matched Right Speaker"
                rightColName = summaryTable.Properties.VariableNames{j};
            end
        end

        if ~isempty(leftColName) && leftColName ~= "All Left Speaker"
            normColName = strcat("Norm ", leftColName);
            if ~ismember(normColName, summaryTable.Properties.VariableNames)
                summaryTable = addvars(summaryTable, zeros(height(summaryTable), 1), 'NewVariableNames', normColName);
            end
            summaryTable{i, normColName} = matchedLeftValue / summaryTable{i, "All Left Speaker"};
        end

        if ~isempty(rightColName) && rightColName ~= "All Right Speaker"
            normColName = strcat("Norm ", rightColName);
            if ~ismember(normColName, summaryTable.Properties.VariableNames)
                summaryTable = addvars(summaryTable, zeros(height(summaryTable), 1), 'NewVariableNames', normColName);
            end
            summaryTable{i, normColName} = matchedRightValue / summaryTable{i, "All Right Speaker"};
        end
        % At this point, summaryTable Normalized value represents the percentage of time spent in the stimulus zone when the stimulus is "active"
        % Note that with this, the range for each normalized stim is [0-1] and is independent of other stimuli (the stims are played sequentially, not simultaneously)
    end



    newCol = strcat(cellstr(summaryTable.("Animal UID")), " > ", cellstr(summaryTable.("Stimulus Task")));
    summaryTable = addvars(summaryTable, categorical(newCol), 'After', 'Stimulus Task', 'NewVariableNames', 'Animal UID by Stim Combo');

    groupedTable = population.metadata.groupby(summaryTable, {'Animal UID by Stim Combo', 'Strain', 'Sex', 'Genotype', 'Stimulus Task'}, 'IncludeEmptyGroups', false);


    % Keep only the required columns and columns that starts with "Norm "
    requiredColumns = {'Strain', 'Sex', 'Genotype', 'Age', 'Stimulus Task', 'Animal UID by Stim Combo'};
    normColumns = startsWith(groupedTable.Properties.VariableNames, "Norm ");
    normColumns = find(normColumns);
    [normColNames, sortIdx] = sort(groupedTable.Properties.VariableNames(normColumns));
    normColumns = normColumns(sortIdx);
    groupedTable = groupedTable(:, [requiredColumns, groupedTable.Properties.VariableNames(normColumns)]);

    % Take the mean of the numeric columns (that starts with "Norm ")
    for i = 1:length(normColNames)
        colName = normColNames{i};
        groupedTable.(colName) = cellfun(@(x) mean(x, "all", "omitnan"), groupedTable.(colName), 'UniformOutput', true);
    end

    normalizedTable = groupedTable;
end