function normalizedTable = normalizeSummaryTable(summaryTable)
    %%NORMALIZESUMMARYTABLE Normalizes the summary table by:
    %   1. Calculate the percentage of Matched Frames over Original Frames for each stimulus and speaker position.
    %   2. Group the trials by Animal UID and Stimulus Task,
    %       If a single animal has multiple trials with the same stimulus task,
    %       average the values for that animal for that stimulus task.
    %
    %   normalizedTable = population.stats.normalizeSummaryTable(summaryTable)
    %
    %   Inputs:
    %       summaryTable - A table generated by population.stats.populationSummary
    %
    %   Outputs:
    %       normalizedTable - A table with normalized values, each row is a unique animal (Animal UID) doing a specific stimulus task (Stimulus Task)
    %
    %   See also: population.stats.populationSummary

    arguments
        summaryTable table
    end

    requiredColumns = {'Strain', 'Sex', 'Genotype', 'Age', 'Cage Code', 'Animal ID', 'Animal UID', 'Stimulus Task'};
    missing = setdiff(requiredColumns, summaryTable.Properties.VariableNames, 'stable');
    if ~isempty(missing)
        error('The provided summaryTable is missing required columns: { ''%s'' }', strjoin(missing, ''', '''));
    end

    newCol = strcat(cellstr(summaryTable.("Animal UID")), " > ", cellstr(summaryTable.("Stimulus Task")));
    summaryTable = addvars(summaryTable, categorical(newCol), 'After', 'Stimulus Task', 'NewVariableNames', 'Animal UID by Stim Combo');

    groupedTable = population.metadata.groupby(summaryTable, {'Animal UID by Stim Combo', 'Strain', 'Sex', 'Genotype', 'Stimulus Task'}, 'IncludeEmptyGroups', false);
    assignin('base', 'groupedTable', groupedTable);
end