function standardizedTables = populationPositionByStim(ethovisionTrials, stimuliDir, masterMetadataTable, kvargs)
    %%POPULATIONPOSITIONBYSTIM Standardize and combine the centerpointData tables from multiple trials for population analysis
    %   Coordinates are interpolated to a common framerate and aligned to stimulus onset times.
    %
    %   standardizedTables = population.stats.populationPositionByStim(ethovisionTrials, stimuliDir, masterMetadataTable)
    %
    %   Inputs:
    %       ethovisionTrials        - A struct array of trialInfo to be included, generated by io.ethovision.filterTrials()
    %       stimuliDir             - Directory containing stimulus files
    %       masterMetadataTable    - The master metadata table loaded from an Excel file with io.metadata.loadMasterMetadata
    %
    %   Name-Value Pair Arguments:
    %       - 'Config': Configuration struct loaded with io.config.loadConfigYaml() to detect the nidaq_audioplayer and/or metadata_extract binary paths.
    %       - 'TargetFPS': Target common framerate (in frames per second) to which position data will be interpolated. Default is 30.
    %       - 'SpeakerFlipAxes': Axis along which to flip when speakers are marked as flipped in the experiment. Options are 'x' or 'y'. Default is 'x'.
    %       - 'Interpolation': Interpolation method to use when interpolating position data to the target framerate. Options are 'linear', 'nearest', 'spline', 'pchip', or 'cubic'. Default is 'spline'.
    %       - 'UIFigure': Handle to a UIFigure, used to parent progress dialogs if desired.
    %
    %   Outputs:
    %       standardizedTables - A struct array of standardized centerpointData tables for each unique stimulus across the population
    %           There are the following fields:
    %               - stimfileName: Name of the stimulus file
    %               - stimuliSorted: Formatted-name of the stimuli pair in the trials of the same kind, sorted alphabetically. If stim name contains "normal" (case-insensitive), that stim is listed first.
    %               - centerpointData: A table with columns 'Trial time', 'X center', 'Y center', 'Distance from Midline', 'Stimulus name', standardized across trials.
    %                   Note that 'X center', 'Y center', and 'Distance from Midline' are multi-column variables in the table, with each column representing a trial aligned to stimulus onset and interpolated to the target framerate.
    %                   The coordinates here are flipped such that negative values are towards stimuliSorted(1) and positive values are towards stimuliSorted(2), according to the speaker flip information in the trial metadata.
    %
    %   See also: io.metadata.loadMasterMetadata, io.config.loadConfigYaml, io.ethovision.filterTrials, trial.stats.trialSummary


    arguments
        ethovisionTrials (:, 1) struct
        stimuliDir {mustBeFolder}
        masterMetadataTable {validator.mustBeFileOrTable}

        kvargs.Config (1,1) struct = struct()
        kvargs.TargetFPS (1,1) double {mustBePositive, mustBeFinite} = 30;
        kvargs.SpeakerFlipAxes {mustBeMember(kvargs.SpeakerFlipAxes, {'x', 'y'}), mustBeTextScalar} = 'x';
        kvargs.Interpolation {mustBeMember(kvargs.Interpolation, {'linear', 'nearest', 'spline', 'pchip', 'cubic'}), mustBeTextScalar} = 'spline';
        kvargs.UIFigure {mustBeUIFigureOrEmpty} = gobjects(0);
    end

    ntrials = length(ethovisionTrials);

    if ntrials == 0
        warning('No trials provided in ethovisionTrials. Returning empty standardizedTables. When using the GUI, select some trials to include in the dropdown tree before running the analysis.');
        standardizedTables = struct.empty();
        return;
    end

    standardizedTables = struct( ...
        'stimfileName', strings(0), ...
        'stimuliSorted', strings(0), ...
        'centerpointData', table() ...
    );
    if ~isempty(kvargs.UIFigure)
        loader = uiprogressdlg(kvargs.UIFigure, ...
            'Title', 'Generating Population Summary', ...
            'Message', 'Loading Trials Metadata...', ...
            'Indeterminate', 'off',...
            'Value', 0,...
            'ShowPercentage', 'on',...
            'Cancelable', 'on');
        cleanupObj = onCleanup(@() close(loader));

        drawnow;
    end

    stimtables = configureDictionary("string", "struct");

    for i = 1:ntrials
        if ~isempty(kvargs.UIFigure)
            if loader.CancelRequested
                warning('Population summary generation canceled while running. Returning partial results.');
                break;
            end
            loader.Message = sprintf('Processing trial %d of %d...', i, ntrials);
            loader.Value = (i-1 + 0.1) / ntrials;
            drawnow;
        end

        [~, centerpointData] = trial.stats.trialSummary(ethovisionTrials(i).data, stimuliDir, masterMetadataTable, Config=kvargs.Config);
        colkey = DataHash(centerpointData.data, 'SHA-256');
        
        colDefault = 'X center |> ';
        % Truncate colkey to namelengthmax - length(colDefault)
        colkey = colkey(1:min(length(colkey), namelengthmax - length(colDefault) - 1));
        
        stimmeta = centerpointData.stimuliMetadata;
        [~, stimfileName, stimfileExt] = fileparts(stimmeta.path);
        stimfileName = sprintf('%s%s', stimfileName, stimfileExt);

        stimKeys = [centerpointData.stimuliCorrected.left, centerpointData.stimuliCorrected.right];
        for j = 1:length(stimKeys)
            if startsWith(stimKeys{j}, '[Ch1] ')
                stimKeys{j} = extractAfter(stimKeys{j}, '[Ch1] ');
            elseif startsWith(stimKeys{j}, '[Ch2] ')
                stimKeys{j} = extractAfter(stimKeys{j}, '[Ch2] ');
            end
        end
        if ~isKey(stimtables, stimfileName)
            stimKeysSorted = sort(stimKeys);
            % If stimtask includes "Normal", bring that task to the front of the list
            normIdx = find(contains(stimKeysSorted, "Normal", 'IgnoreCase', true), 1);
            if ~isempty(normIdx) && normIdx ~= 1
                stimKeysSorted = [stimKeysSorted(normIdx), stimKeysSorted(setdiff(1:end, normIdx))];
            end
            
            stimtables(stimfileName) = struct( ...
                'stimfileName', stimfileName, ...
                'stimuliSorted', stimKeysSorted, ...
                'centerpointData', table() ...
            );

            t = makeTemplateTableByStim(stimmeta, kvargs.TargetFPS);
            stimtables(stimfileName).centerpointData = t;
        end


        thisTrialTime = centerpointData.data{:, 'Trial time'};
        thisX = centerpointData.data{:, 'X center'};
        thisY = centerpointData.data{:, 'Y center'};
        % Interpolate to the standardized timepoints
        standardizedTime = stimtables(stimfileName).centerpointData{:, 'Trial time'};
        standardizedStims = stimtables(stimfileName).centerpointData{:, 'Stimulus name'};
        interpX = interp1(thisTrialTime, thisX, standardizedTime, kvargs.Interpolation, 'extrap');
        interpY = interp1(thisTrialTime, thisY, standardizedTime, kvargs.Interpolation, 'extrap');
        centerpointData.data = table();
        centerpointData.data.('Trial time') = standardizedTime;
        centerpointData.data.('Stimulus name') = standardizedStims;
        centerpointData.data.('X center') = interpX;
        centerpointData.data.('Y center') = interpY;


        % If stimKeys(1) is not the same as stimuliSorted(1), mirror the relevant axis by the midline_*offset_px
        flipCondition = false;
        if strcmpi(kvargs.SpeakerFlipAxes, 'x')
            if ~strcmpi(stimKeys(1), stimtables(stimfileName).stimuliSorted(1))
                flipCondition = true;
            end
            xcenterData = centerpointData.data{:, 'X center'};
            midlineX_cm = centerpointData.midline_xoffset_px * centerpointData.px2cm; % since data is in cm
            if flipCondition
                % mirror horizontally around midlineX
                xcenterData = 2 * midlineX_cm - xcenterData;
            end
            centerpointData.data{:, 'X center'} = xcenterData;
            % Calculate a Dist to Midline column that is the distance from the midline
            centerpointData.data{:, 'Distance from Midline'} = xcenterData - midlineX_cm; % negative should be towards stimuliSorted(1), positive towards stimuliSorted(2)
        elseif strcmpi(kvargs.SpeakerFlipAxes, 'y')
            if ~strcmpi(stimKeys(1), stimtables(stimfileName).stimuliSorted(1))
                flipCondition = true;
            end
            ycenterData = centerpointData.data{:, 'Y center'};
            midlineY_cm = centerpointData.midline_yoffset_px * centerpointData.px2cm;
            if flipCondition
                % mirror vertically around midlineY
                ycenterData = 2 * midlineY_cm - ycenterData;
            end
            centerpointData.data{:, 'Y center'} = ycenterData;
            centerpointData.data{:, 'Distance from Midline'} = ycenterData - midlineY_cm;
        else
            % This should not happen due to argument validation
            error('Invalid SpeakerFlipAxes value: %s. Must be ''x'' or ''y''.', kvargs.SpeakerFlipAxes);
        end


        % Rename the centerpointData XY columns to include trial key
        centerpointData.data.Properties.VariableNames{'X center'} = sprintf('X center |> %s', colkey);
        centerpointData.data.Properties.VariableNames{'Y center'} = sprintf('Y center |> %s', colkey);
        centerpointData.data.Properties.VariableNames{'Distance from Midline'} = sprintf('Distance from Midline |> %s', colkey);

        % If the table is empty, just assign
        if isempty(stimtables(stimfileName).centerpointData)
            stimtables(stimfileName).centerpointData = centerpointData.data;
        else
            % Otherwise, join the tables on 'Trial time' and 'Stimulus name'
            stimtables(stimfileName).centerpointData = outerjoin( ...
                stimtables(stimfileName).centerpointData, ...
                centerpointData.data, ...
                'Keys', {'Trial time', 'Stimulus name'}, ...
                'MergeKeys', true ...
            );
        end

    end

    % For each table in stimtables, mergevars on columns that start with 'X center |>' and 'Y center |>' so that they become multi-column variables
    stimfileNames = keys(stimtables);
    for i = 1:length(stimfileNames)
        stimfileName = stimfileNames{i};
        tbl = stimtables(stimfileName).centerpointData;

        xCenterCols = startsWith(tbl.Properties.VariableNames, 'X center |> ');
        tbl = mergevars(tbl, tbl.Properties.VariableNames(xCenterCols), 'NewVariableName', 'X center');        
        yCenterCols = startsWith(tbl.Properties.VariableNames, 'Y center |> ');
        tbl = mergevars(tbl, tbl.Properties.VariableNames(yCenterCols), 'NewVariableName', 'Y center');
        distanceCols = startsWith(tbl.Properties.VariableNames, 'Distance from Midline |> ');
        tbl = mergevars(tbl, tbl.Properties.VariableNames(distanceCols), 'NewVariableName', 'Distance from Midline');

        stimtables(stimfileName).centerpointData = tbl;

        % Append to standardizedTables
        standardizedTables(end+1) = stimtables(stimfileName); %#ok<AGROW>
    end

    % Remove the initial empty element
    standardizedTables = standardizedTables(2:end);

    if ~isempty(kvargs.UIFigure)
        loader.Value = 1;
        loader.Message = 'Population Summary Generation Complete.';
        pause(0.1); % Pause to allow user to see completion
    end

    %% FIGURE

    assignin("base", "standardizedTables", standardizedTables); % for debugging






end


function mustBeUIFigureOrEmpty(x)
    if ~isempty(x) && ~matlab.ui.internal.isUIFigure(x)
        error('If provided, UIFigure must be a handle to a MATLAB UIFigure created with uifigure().');
    end
end



function t = makeTemplateTableByStim(stimuliMetadata, targetFPS)
    arguments
        stimuliMetadata (1,1) struct
        targetFPS (1,1) double {mustBePositive, mustBeFinite}
    end


    duration = stimuliMetadata.duration; % in seconds
    
    % number of frames that is within the duration at targetFPS
    nframes = ceil(duration * targetFPS);
    frametime = (0:(nframes-1))' / targetFPS;
    t = table();
    t.('Trial time') = frametime;
    
    
    if ~isfield(stimuliMetadata, 'chapters') || isempty(stimuliMetadata.chapters) || ~isfield(stimuliMetadata.chapters, 'timestamp') || isempty([stimuliMetadata.chapters.timestamp])
        % Maybe show a warning here that no stimuli columns are created?
        return;
    end

    chapters = stimuliMetadata.chapters;
    chapterTimestamps = [chapters.timestamp]; % in seconds
    chapterTitles = {chapters.title};

    % Match each frametime to a corresponding chapter
    % Use discretize for efficient chapter assignment than looping over each frame
    chapterIndices = discretize(frametime, [-inf, chapterTimestamps, inf]);
    
    % Adjust indices (discretize returns bin number, we want the last valid chapter)
    chapterIndices = max(1, chapterIndices - 1);
    chapterIndices(chapterIndices == 0) = 1; % Handle edge case
    chapterIndices = min(chapterIndices, length(chapters)); % Ensure valid indices
    
    % Vectorized assignment of chapter titles
    validMask = chapterIndices >= 1 & chapterIndices <= length(chapters);

    validChapterIndices = chapterIndices(validMask);
    assignedTitles = chapterTitles(validChapterIndices)';

    t.('Stimulus name') = strings(height(t), 1);
    t.('Stimulus name')(validMask) = assignedTitles;
end