function standardizedTables = populationPositionOverTime(ethovisionTrials, stimuliDir, masterMetadataTable, kvargs)
    %%POPULATIONPOSITIONOVERTIME Standardize and combine the centerpointData tables from multiple trials for population analysis
    %   Coordinates are interpolated to a common framerate and aligned to stimulus onset times.
    %
    %   standardizedTables = population.stats.populationPositionOverTime(ethovisionTrials, stimuliDir, masterMetadataTable)
    %
    %   Inputs:
    %       ethovisionTrials        - A struct array of trialInfo to be included, generated by io.ethovision.filterTrials()
    %       stimuliDir             - Directory containing stimulus files
    %       masterMetadataTable    - The master metadata table loaded from an Excel file with io.metadata.loadMasterMetadata
    %
    %   Name-Value Pair Arguments:
    %       - 'Config': Configuration struct loaded with io.config.loadConfigYaml() to detect the nidaq_audioplayer and/or metadata_extract binary paths.
    %       - 'TargetFPS': Target common framerate (in frames per second) to which position data will be interpolated. Default is 30.
    %       - 'SpeakerFlipAxes': Axis along which to flip when speakers are marked as flipped in the experiment. Options are 'x' or 'y'. Default is 'x'.
    %       - 'Interpolation': Interpolation method to use when interpolating position data to the target framerate. Options are 'linear', 'nearest', 'spline', 'pchip', or 'cubic'. Default is 'spline'.
    %       - 'UIFigure': Handle to a UIFigure, used to parent progress dialogs if desired.
    %
    %   Outputs:
    %       standardizedTables - A struct array of standardized centerpointData tables for each unique stimulus across the population
    %           There are the following fields:
    %               - stimfileName: Name of the stimulus file
    %               - stimuliSorted: Formatted-name of the stimuli pair in the trials of the same kind, sorted alphabetically. If stim name contains "normal" (case-insensitive), that stim is listed first.
    %               - animalMetadata: A dictionary (string-struct) in the order of columns in centerpointData, where each key is a hash key corresponding to a trial's centerpointData, and each value is the animal metadata struct for that trial.
    %               - centerpointData: A table with columns 'Trial time', 'X center', 'Y center', 'Distance from Midline', 'Stimulus name', standardized across trials.
    %                   Note that 'X center', 'Y center', and 'Distance from Midline' are multi-column variables in the table, with each column representing a trial aligned to stimulus onset and interpolated to the target framerate.
    %                   The coordinates here are flipped such that negative values are towards stimuliSorted(1) and positive values are towards stimuliSorted(2), according to the speaker flip information in the trial metadata.
    %
    %   See also: io.metadata.loadMasterMetadata, io.config.loadConfigYaml, io.ethovision.filterTrials, trial.stats.trialSummary


    arguments
        ethovisionTrials (:, 1) struct
        stimuliDir {mustBeFolder}
        masterMetadataTable {validator.mustBeFileOrTable}

        kvargs.Config (1,1) struct = struct()
        kvargs.TargetFPS (1,1) double {mustBePositive, mustBeFinite} = 30;
        kvargs.SpeakerFlipAxes {mustBeMember(kvargs.SpeakerFlipAxes, {'x', 'y'}), mustBeTextScalar} = 'x';
        % https://www.mathworks.com/help/matlab/ref/double.interp1.html#btwp6lt-1-method
        % linear is good but may produce NaN
        % spline is often best, but if the data is sparse (missing lots of nearby points), can produce overshoot artifacts
        % pchip is a good compromise that avoids overshoot, but less smooth and flatten missing data points more aggressively (though, for place preference, this may be desirable)
        kvargs.Interpolation {mustBeMember(kvargs.Interpolation, {'linear', 'nearest', 'spline', 'makima', 'pchip', 'cubic'}), mustBeTextScalar} = 'pchip';
        kvargs.UIFigure {mustBeUIFigureOrEmpty} = gobjects(0);
    end

    ntrials = length(ethovisionTrials);

    if ntrials == 0
        warning('No trials provided in ethovisionTrials. Returning empty standardizedTables. When using the GUI, select some trials to include in the dropdown tree before running the analysis.');
        standardizedTables = struct.empty();
        return;
    end

    standardizedTables = struct( ...
        'stimfileName', strings(0), ...
        'stimuliSorted', strings(0), ...
        'animalMetadata', configureDictionary("string", "struct"), ...
        'centerpointData', table() ...
    );
    if ~isempty(kvargs.UIFigure)
        loader = uiprogressdlg(kvargs.UIFigure, ...
            'Title', 'Generating Population Summary', ...
            'Message', 'Loading Trials Metadata...', ...
            'Indeterminate', 'off',...
            'Value', 0,...
            'ShowPercentage', 'on',...
            'Cancelable', 'on');
        cleanupObj = onCleanup(@() close(loader));

        drawnow;
    end


    % MidlineX and midlineY, in px, top-left is (0,0), corrected by the relevant .midpoint.csv or .midline.csv data depending on config's defaults.distance2refmode
    refmode = 'line'; % default
    fromConfigKey = {'defaults', 'distance2refmode'};
    if validator.nestedStructFieldExists(kvargs.Config, fromConfigKey)
        refmode = getfield(kvargs.Config, fromConfigKey{:});
        if iscell(refmode)
            refmode = string(refmode{1});
        end
        if ~ismember(refmode, ["point", "line"])
            refmode = 'line'; % fallback to default
            warning("population:stats:populationPositionOverTime:InvalidConfig", "Invalid config value for 'defaults.distance2refmode': %s. Falling back to 'line'.", refmode);
        end
    end

    stimtables = configureDictionary("string", "struct");
    animalMetadataDict = configureDictionary("string", "struct");

    for i = 1:ntrials
        if ~isempty(kvargs.UIFigure)
            if loader.CancelRequested
                warning('Population position-by-stim generation canceled while running. Returning partial results.');
                break;
            end
            loader.Message = sprintf('Processing trial %d of %d...', i, ntrials);
            loader.Value = (i-1 + 0.1) / ntrials;
            drawnow;
        end
        
        [summary, centerpointData] = trial.stats.trialSummary(ethovisionTrials(i).data, stimuliDir, masterMetadataTable, Config=kvargs.Config);
        % Regardless of what is in config for refmode, we should prioritize what was used in trialSummary by inferring from the size() of centerpointData.midline_x_px and midline_x_px
        if isfield(centerpointData, 'midline_x_px') && ~isempty(centerpointData.midline_x_px)
            % Assert the size of midline_x_px and midline_y_px is the same
            assert(isequal(size(centerpointData.midline_x_px), size(centerpointData.midline_y_px)), ...
                'population:stats:populationPositionOverTime:MidlineSizeMismatch', ...
                'Size mismatch between midline_x_px and midline_y_px in trial %d centerpointData.', i);
            % If midline_x_px and midline_y_px are scalars, then refmode is 'point', else 'line'
            if isscalar(centerpointData.midline_x_px)
                refmode = 'point';
            else
                refmode = 'line';
            end 
        end
        % Also note that if config specifies xflip/yflip, those were already applied in trialSummary
        % flipCondition below only determines whether to flip based on speaker sides to normalize all trials to the same orientation


        stimmeta = centerpointData.stimuliMetadata;
        [~, stimfileName, stimfileExt] = fileparts(stimmeta.path);
        stimfileName = sprintf('%s%s', stimfileName, stimfileExt);

        stimKeys = [centerpointData.stimuliCorrected.left, centerpointData.stimuliCorrected.right];
        for j = 1:length(stimKeys)
            if startsWith(stimKeys{j}, '[Ch1] ')
                stimKeys{j} = extractAfter(stimKeys{j}, '[Ch1] ');
            elseif startsWith(stimKeys{j}, '[Ch2] ')
                stimKeys{j} = extractAfter(stimKeys{j}, '[Ch2] ');
            end
        end
        if ~isKey(stimtables, stimfileName)
            stimKeysSorted = sort(stimKeys);
            % If stimtask includes "Normal", bring that task to the front of the list
            normIdx = find(contains(stimKeysSorted, "Normal", 'IgnoreCase', true), 1);
            if ~isempty(normIdx) && normIdx ~= 1
                stimKeysSorted = [stimKeysSorted(normIdx), stimKeysSorted(setdiff(1:end, normIdx))];
            end
            
            stimtables(stimfileName) = struct( ...
                'stimfileName', stimfileName, ...
                'stimuliSorted', stimKeysSorted, ...
                'animalMetadata', configureDictionary("string", "struct"), ... % This will be empty till the end when all trials are processed
                'centerpointData', table() ...
            );

            t = makeTemplateTableByStim(stimmeta, kvargs.TargetFPS);
            stimtables(stimfileName).centerpointData = t;
        end


        thisTrialTime = centerpointData.data{:, 'Trial time'};
        thisX = centerpointData.data{:, 'X center'};
        thisY = centerpointData.data{:, 'Y center'};
        % Interpolate to the standardized timepoints
        standardizedTime = stimtables(stimfileName).centerpointData{:, 'Trial time'};
        standardizedStims = stimtables(stimfileName).centerpointData{:, 'Stimulus name'};
        warning('off', 'MATLAB:interp1:NaNstrip');
        interpX = interp1(thisTrialTime, thisX, standardizedTime, kvargs.Interpolation, 'extrap');
        interpY = interp1(thisTrialTime, thisY, standardizedTime, kvargs.Interpolation, 'extrap');
        warning('on', 'MATLAB:interp1:NaNstrip');
        centerpointData.data = table();
        centerpointData.data.('Trial time') = standardizedTime;
        centerpointData.data.('Stimulus name') = standardizedStims;
        centerpointData.data.('X center') = interpX;
        centerpointData.data.('Y center') = interpY;


        % If stimKeys(1) is not the same as stimuliSorted(1), mirror the relevant axis by the midline_*offset_px
        flipCondition = false;
        midlineX_cm = centerpointData.midline_x_px * centerpointData.px2cm; % since data is in cm
        midlineY_cm = centerpointData.midline_y_px * centerpointData.px2cm;
        if strcmpi(kvargs.SpeakerFlipAxes, 'x')
            if ~strcmpi(stimKeys(1), stimtables(stimfileName).stimuliSorted(1))
                flipCondition = true;
            end
            if flipCondition
                if strcmpi(refmode, 'point')
                    xcenterData = centerpointData.data{:, 'X center'};
                    xcenterData = 2 * midlineX_cm - xcenterData;
                    centerpointData.data{:, 'X center'} = xcenterData;
                elseif strcmpi(refmode, 'line')
                    points = [centerpointData.data{:, 'X center'}, centerpointData.data{:, 'Y center'}];
                    lineX = [midlineX_cm(1), midlineX_cm(end)];
                    lineY = [midlineY_cm(1), midlineY_cm(end)];
                    mirroredPoints = mirrorPointsAcrossLine(points, lineX, lineY);
                    centerpointData.data{:, 'X center'} = mirroredPoints(:,1);
                    centerpointData.data{:, 'Y center'} = mirroredPoints(:,2);
                end
            end

            % Calculate a Dist to Midline column that is the distance from the midline
            % centerpointData.data{:, 'Distance from Midline'} = xcenterData - midlineX_cm; % negative should be towards stimuliSorted(1), positive towards stimuliSorted(2)
            if strcmpi(refmode, 'point')
                % Euclidean distance from reference point on midline
                xcenterData = centerpointData.data{:, 'X center'};
                ycenterData = centerpointData.data{:, 'Y center'};
                distFromMidline = sqrt( (xcenterData - midlineX_cm).^2 + (ycenterData - midlineY_cm).^2 );
                % Determine sign based on which side of the midline the subject is on
                signMask = sign(xcenterData - midlineX_cm);
                distFromMidline = distFromMidline .* signMask; % negative towards stimuliSorted(1), positive towards stimuliSorted(2)
                centerpointData.data{:, 'Distance from Midline'} = distFromMidline;
            elseif strcmpi(refmode, 'line')
                % Calculate perpendicular distance to line defined by midlineX_cm and midlineY_cm
                points = [centerpointData.data{:, 'X center'}, centerpointData.data{:, 'Y center'}];
                lineX = [midlineX_cm(1), midlineX_cm(end)];
                lineY = [midlineY_cm(1), midlineY_cm(end)];
                % Line equation: Ax + By + C = 0
                A = lineY(1) - lineY(2);
                B = lineX(2) - lineX(1);
                C = -A*lineX(1) - B*lineY(1);
                M = A^2 + B^2;
                if M > 0
                    val = A .* points(:,1) + B .* points(:,2) + C;
                    distToLine = val / sqrt(M);
                    centerpointData.data{:, 'Distance from Midline'} = distToLine; % negative should be towards stimuliSorted(1), positive towards stimuliSorted(2)
                else
                    centerpointData.data{:, 'Distance from Midline'} = zeros(height(centerpointData.data), 1); % degenerate case, line is invalid
                end
            end

        elseif strcmpi(kvargs.SpeakerFlipAxes, 'y')
            if ~strcmpi(stimKeys(1), stimtables(stimfileName).stimuliSorted(1))
                flipCondition = true;
            end
            if flipCondition
                if strcmpi(refmode, 'point')
                    ycenterData = centerpointData.data{:, 'Y center'};
                    ycenterData = 2 * midlineY_cm - ycenterData;
                    centerpointData.data{:, 'Y center'} = ycenterData;
                elseif strcmpi(refmode, 'line')
                    points = [centerpointData.data{:, 'X center'}, centerpointData.data{:, 'Y center'}];
                    lineX = [midlineY_cm(1), midlineY_cm(end)]; % swap x and y for vertical mirroring
                    lineY = [midlineX_cm(1), midlineX_cm(end)];
                    mirroredPoints = mirrorPointsAcrossLine(points, lineX, lineY);
                    centerpointData.data{:, 'X center'} = mirroredPoints(:,1);
                    centerpointData.data{:, 'Y center'} = mirroredPoints(:,2);
                end
            end
            if strcmpi(refmode, 'point')
                % Euclidean distance from reference point on midline
                xcenterData = centerpointData.data{:, 'X center'};
                ycenterData = centerpointData.data{:, 'Y center'};
                distFromMidline = sqrt( (xcenterData - midlineX_cm).^2 + (ycenterData - midlineY_cm).^2 );
                % Determine sign based on which side of the midline the subject is on
                signMask = sign(ycenterData - midlineY_cm);
                distFromMidline = distFromMidline .* signMask; % negative towards stimuliSorted(1), positive towards stimuliSorted(2)
                centerpointData.data{:, 'Distance from Midline'} = distFromMidline;
            elseif strcmpi(refmode, 'line')
                % Calculate perpendicular distance to line defined by midlineX_cm and midlineY_cm
                points = [centerpointData.data{:, 'X center'}, centerpointData.data{:, 'Y center'}];
                lineX = [midlineX_cm(1), midlineX_cm(end)];
                lineY = [midlineY_cm(1), midlineY_cm(end)];
                % Line equation: Ax + By + C = 0
                A = lineY(1) - lineY(2);
                B = lineX(2) - lineX(1);
                C = -A*lineX(1) - B*lineY(1);
                M = A^2 + B^2;
                if M > 0
                    val = A .* points(:,1) + B .* points(:,2) + C;
                    distToLine = val / sqrt(M);
                    centerpointData.data{:, 'Distance from Midline'} = distToLine; % negative should be towards stimuliSorted(1), positive towards stimuliSorted(2)
                else
                    centerpointData.data{:, 'Distance from Midline'} = zeros(height(centerpointData.data), 1); % degenerate case, line is invalid
                end
            end
        else
            % This should not happen due to argument validation
            error('Invalid SpeakerFlipAxes value: %s. Must be ''x'' or ''y''.', kvargs.SpeakerFlipAxes);
        end


        colkey = DataHash(centerpointData.data, 'SHA-256');
        colDefault = 'X center |> ';
        % Truncate colkey to namelengthmax - length(colDefault)
        colkey = colkey(1:min(length(colkey), namelengthmax - length(colDefault) - 1));
        
        % Save the animal info for this trial by its hash key
        if ~isKey(animalMetadataDict, colkey)
            animalMetadataDict(colkey) = summary.animalMetadata;
        else
            error('population:stats:populationPositionOverTime:DuplicateAnimalMetadataKey', ...
                'Duplicate animal metadata key detected for trial %d.\nIn extremely rare cases, this could indicate SHA-256 hash collision of the behavioral center-point position for the trial. In practice, this should not happen, unless you know for a matter of fact that 2 trials have identical behavioral data. If you see this message, please check your trial.stats.trialSummary(_) output as the centerpointData output might be malformed or empty.\nAffected hash key: %s\nAssociated animal metadata: %s', i, colkey, utils.io.structprettyprint(summary.animalMetadata, 4, Inf));
        end

        % Rename the centerpointData XY columns to include trial key
        centerpointData.data.Properties.VariableNames{'X center'} = sprintf('X center |> %s', colkey);
        centerpointData.data.Properties.VariableNames{'Y center'} = sprintf('Y center |> %s', colkey);
        centerpointData.data.Properties.VariableNames{'Distance from Midline'} = sprintf('Distance from Midline |> %s', colkey);

        % If the table is empty, just assign
        if isempty(stimtables(stimfileName).centerpointData)
            stimtables(stimfileName).centerpointData = centerpointData.data;
        else
            % Otherwise, join the tables on 'Trial time' and 'Stimulus name'
            stimtables(stimfileName).centerpointData = outerjoin( ...
                stimtables(stimfileName).centerpointData, ...
                centerpointData.data, ...
                'Keys', {'Trial time', 'Stimulus name'}, ...
                'MergeKeys', true ...
            );
        end
    end

    % For each table in stimtables, mergevars on columns that start with 'X center |>' and 'Y center |>' so that they become multi-column variables
    stimfileNames = keys(stimtables);
    for i = 1:length(stimfileNames)
        stimfileName = stimfileNames{i};
        tbl = stimtables(stimfileName).centerpointData;

        xCenterCols = startsWith(tbl.Properties.VariableNames, 'X center |> ');
        % Get the keys for these columns to retrieve animalMetadata related to them
        xCenterKeys = cellfun(@(colname) extractAfter(colname, 'X center |> '), tbl.Properties.VariableNames(xCenterCols), 'UniformOutput', false);
        % Subset the dictionary to only include these keys, ensure order
        animalMetadataSubDict = configureDictionary("string", "struct");
        for j = 1:length(xCenterKeys)
            key = xCenterKeys{j};
            if isKey(animalMetadataDict, key)
                animalMetadataSubDict(key) = animalMetadataDict(key);
            else
                error('population:stats:populationPositionOverTime:MissingAnimalMetadataKey', ...
                    'Missing animal metadata key detected for stimulus file %s. Something extremely weird has happened...\nMissing key: %s', stimfileName, key);
            end
        end
        tbl = mergevars(tbl, tbl.Properties.VariableNames(xCenterCols), 'NewVariableName', 'X center');
        yCenterCols = startsWith(tbl.Properties.VariableNames, 'Y center |> ');
        tbl = mergevars(tbl, tbl.Properties.VariableNames(yCenterCols), 'NewVariableName', 'Y center');
        distanceCols = startsWith(tbl.Properties.VariableNames, 'Distance from Midline |> ');
        tbl = mergevars(tbl, tbl.Properties.VariableNames(distanceCols), 'NewVariableName', 'Distance from Midline');

        stimtables(stimfileName).centerpointData = tbl;
        stimtables(stimfileName).animalMetadata = animalMetadataSubDict;

        % Append to standardizedTables
        standardizedTables(end+1) = stimtables(stimfileName); %#ok<AGROW>
    end

    % Remove the initial empty element
    standardizedTables = standardizedTables(2:end);

    if ~isempty(kvargs.UIFigure)
        loader.Value = 1;
        loader.Message = 'Population Summary Generation Complete.';
        pause(0.1); % Pause to allow user to see completion
    end

    %% FIGURE?

    assignin("base", "standardizedTables", standardizedTables); % for debugging






end


function mustBeUIFigureOrEmpty(x)
    if ~isempty(x) && ~matlab.ui.internal.isUIFigure(x)
        error('If provided, UIFigure must be a handle to a MATLAB UIFigure created with uifigure().');
    end
end



function t = makeTemplateTableByStim(stimuliMetadata, targetFPS)
    arguments
        stimuliMetadata (1,1) struct
        targetFPS (1,1) double {mustBePositive, mustBeFinite}
    end


    duration = stimuliMetadata.duration; % in seconds
    
    % number of frames that is within the duration at targetFPS
    nframes = ceil(duration * targetFPS);
    frametime = (0:(nframes-1))' / targetFPS;
    t = table();
    t.('Trial time') = frametime;
    
    
    if ~isfield(stimuliMetadata, 'chapters') || isempty(stimuliMetadata.chapters) || ~isfield(stimuliMetadata.chapters, 'timestamp') || isempty([stimuliMetadata.chapters.timestamp])
        % Maybe show a warning here that no stimuli columns are created?
        return;
    end

    chapters = stimuliMetadata.chapters;
    chapterTimestamps = [chapters.timestamp]; % in seconds
    chapterTitles = {chapters.title};

    % Match each frametime to a corresponding chapter
    % Use discretize for efficient chapter assignment than looping over each frame
    chapterIndices = discretize(frametime, [-inf, chapterTimestamps, inf]);
    
    % Adjust indices (discretize returns bin number, we want the last valid chapter)
    chapterIndices = max(1, chapterIndices - 1);
    chapterIndices(chapterIndices == 0) = 1; % Handle edge case
    chapterIndices = min(chapterIndices, length(chapters)); % Ensure valid indices
    
    % Vectorized assignment of chapter titles
    validMask = chapterIndices >= 1 & chapterIndices <= length(chapters);

    validChapterIndices = chapterIndices(validMask);
    assignedTitles = chapterTitles(validChapterIndices)';

    t.('Stimulus name') = strings(height(t), 1);
    t.('Stimulus name')(validMask) = assignedTitles;
end


function points = mirrorPointsAcrossLine(points, lineX, lineY)
    % Define line passing through P1(x1,y1) and P2(x2,y2)
    x1 = lineX(1); y1 = lineY(1);
    x2 = lineX(2); y2 = lineY(2);
    
    % Line equation: Ax + By + C = 0
    A = y1 - y2;
    B = x2 - x1;
    C = -A*x1 - B*y1;
    
    % Calculate reflection
    M = A^2 + B^2;
    if M > 0
        val = A .* points(:,1) + B .* points(:,2) + C;
        factor = -2 * val / M;
        points(:,1) = points(:,1) + factor * A;
        points(:,2) = points(:,2) + factor * B;
    end
end