function summaryTable = populationSummary(ethovisionTrials, stimuliDir, masterMetadataTable, kvargs)
    %%POPULATIONSUMMARY Summarize population information from master metadata table
    %
    %   summaryTable = population.stats.populationSummary(ethovisionTrials, stimuliDir, masterMetadataTable)
    %
    %   Inputs:
    %       ethovisionTrials        - A struct array of trialInfo to be included, generated by io.ethovision.filterTrials()
    %       stimuliDir             - Directory containing stimulus files
    %       masterMetadataTable    - The master metadata table loaded from an Excel file with io.metadata.loadMasterMetadata
    %
    %   Name-Value Pair Arguments:
    %       - 'Config': Configuration struct loaded with io.config.loadConfigYaml() to detect the nidaq_audioplayer and/or metadata_extract binary paths.
    %       - 'UIFigure': Handle to a UIFigure, used to parent progress dialogs if desired.
    %
    %   Outputs:
    %       summaryTable - A table summarizing population information
    %
    %   See also: io.metadata.loadMasterMetadata, io.config.loadConfigYaml, io.ethovision.filterTrials, trial.stats.trialSummary


    arguments
        ethovisionTrials (:, 1) struct
        stimuliDir {mustBeFolder}
        masterMetadataTable {validator.mustBeFileOrTable}

        kvargs.Config (1,1) struct = struct()
        kvargs.UIFigure {mustBeUIFigureOrEmpty} = gobjects(0);
    end

    ntrials = length(ethovisionTrials);

    if ntrials == 0
        warning('No trials provided in ethovisionTrials. Returning empty summaryTable. When using the GUI, select some trials to include in the dropdown tree before running the analysis.');
        summaryTable = table();
        return;
    end

    summaryTable = table();

    if ~isempty(kvargs.UIFigure)
        loader = uiprogressdlg(kvargs.UIFigure, ...
            'Title', 'Generating Population Summary', ...
            'Message', 'Loading Trials Metadata...', ...
            'Indeterminate', 'off',...
            'Value', 0,...
            'ShowPercentage', 'on',...
            'Cancelable', 'on');
        cleanupObj = onCleanup(@() close(loader));

        drawnow;
    end

    for i = 1:ntrials
        if ~isempty(kvargs.UIFigure)
            if loader.CancelRequested
                warning('Population summary generation canceled while running. Returning partial results.');
                break;
            end
            loader.Message = sprintf('Processing trial %d of %d...', i, ntrials);
            loader.Value = (i-1 + 0.1) / ntrials;
            drawnow;
        end

        trialSummary = trial.stats.trialSummary(ethovisionTrials(i).data, stimuliDir, masterMetadataTable, Config=kvargs.Config);
        animalMeta = trialSummary.animalMetadata;
        animalMatchedStim = trialSummary.animalMatchedStim;
        stimspeakerMatched = trialSummary.stimspeakerMatched;
        stimspeakerOriginal = trialSummary.stimspeakerOriginal;

        stimNames = keys(animalMatchedStim);
        stimsCleaned = stimNames; % Initialize cleaned stims
        for j = 1:numel(stimNames)
            if startsWith(stimNames{j}, '[Ch1] ')
                stimsCleaned{j} = extractAfter(stimNames{j}, '[Ch1] ');
            elseif startsWith(stimNames{j}, '[Ch2] ')
                stimsCleaned{j} = extractAfter(stimNames{j}, '[Ch2] ');
            end
        end
        stimsCleanedSorted = sort(stimsCleaned); % Ensure that the same stimuli pair in different orders are treated as one
        stimTask = strjoin(stimsCleanedSorted, ' || ');
        clear stimsCleanedSorted;

        if ~isnumeric(animalMeta.age)
            animalMeta.age = str2double(string(animalMeta.age));
        end

        metaKeys = {'Strain', 'Sex', 'Genotype', 'Age', 'Cage Code', 'Animal ID', 'Animal UID', 'Stimulus Task'};
        newRow = table( ...
            categorical(cellstr(animalMeta.strain)), categorical(cellstr(animalMeta.sex)), categorical(cellstr(animalMeta.genotype)), ...
            animalMeta.age, categorical(cellstr(animalMeta.cagecode)), categorical(cellstr(animalMeta.id)), ...
            categorical(strjoin([string(animalMeta.cagecode), string(animalMeta.id)], ' - ')), categorical(cellstr(stimTask)), ...
            'VariableNames', metaKeys);

        for j = 1:numel(stimsCleaned)
            if ~ismember(stimsCleaned{j}, summaryTable.Properties.VariableNames)
                summaryTable = addvars(summaryTable, zeros(height(summaryTable), 1), 'NewVariableNames', stimsCleaned(j));
            end
        end
        
        matchedSpeakerPositions = keys(stimspeakerMatched);
        matchedSpeakerPositionKeys = strcat("Matched ", string(matchedSpeakerPositions));
        for j = 1:numel(matchedSpeakerPositions)
            if ~ismember(matchedSpeakerPositionKeys{j}, summaryTable.Properties.VariableNames)
                summaryTable = addvars(summaryTable, zeros(height(summaryTable), 1), 'NewVariableNames', matchedSpeakerPositionKeys(j));
            end
        end
        allSpeakerPositions = keys(stimspeakerOriginal);
        allSpeakerPositionKeys = strcat("All ", string(allSpeakerPositions));
        for j = 1:numel(allSpeakerPositions)
            if ~ismember(allSpeakerPositionKeys{j}, summaryTable.Properties.VariableNames)
                summaryTable = addvars(summaryTable, zeros(height(summaryTable), 1), 'NewVariableNames', allSpeakerPositionKeys(j));
            end
        end

        % With this genotype group + matched stim data, fill missing with 0s
        % Make sure the tables have same number of vars
        for j = 1:numel(stimNames)
            newRow.(stimsCleaned{j}) = animalMatchedStim(stimNames{j});
        end
        for j = 1:numel(matchedSpeakerPositions)
            newRow.(matchedSpeakerPositionKeys{j}) = stimspeakerMatched(matchedSpeakerPositions{j});
        end
        for j = 1:numel(allSpeakerPositions)
            newRow.(allSpeakerPositionKeys{j}) = stimspeakerOriginal(allSpeakerPositions{j});
        end
        warning('off', 'MATLAB:table:RowsAddedExistingVars');
        summaryTable(end+1:end+height(newRow), newRow.Properties.VariableNames) = newRow;
        warning('on', 'MATLAB:table:RowsAddedExistingVars');
    end

    % Move the metaKeys columns to the front
    [~, metaIdx] = ismember(metaKeys, summaryTable.Properties.VariableNames);
    summaryTable = summaryTable(:, [metaIdx, setdiff(1:width(summaryTable), metaIdx)]);

end


function mustBeUIFigureOrEmpty(x)
    if ~isempty(x) && ~matlab.ui.internal.isUIFigure(x)
        error('If provided, UIFigure must be a handle to a MATLAB UIFigure created with uifigure().');
    end
end