function [bool, missing] = available(requiredExtensions)
    %%AVAILABLE Check if MatNWB and required extensions are installed
    arguments
        requiredExtensions (1,:) string {mustBeMember(requiredExtensions, [...
            "ndx-miniscope", ...
            "ndx-simulation-output", ...
            "ndx-ecog", ...
            "ndx-fret", ...
            "ndx-icephys-meta", ...
            "ndx-events", ...
            "ndx-nirs", ...
            "ndx-hierarchical-behavioral-data", ...
            "ndx-sound", ...
            "ndx-extract", ...
            "ndx-photometry", ...
            "ndx-acquisition-module", ...
            "ndx-odor-metadata", ...
            "ndx-whisk", ...
            "ndx-ecg", ...
            "ndx-franklab-novela", ...
            "ndx-photostim", ...
            "ndx-multichannel-volume", ...
            "ndx-depth-moseq", ...
            "ndx-probeinterface", ...
            "ndx-dbs", ...
            "ndx-hed", ...
            "ndx-ophys-devices", ...
            "ndx-microscopy", ...
            "ndx-pose", ...
            "ndx-fiber-photometry", ...
            "ndx-binned-spikes", ...
            "ndx-wearables", ...
            "ndx-fscv" ...
            ] ...
        )} = ["ndx-pose", "ndx-sound"]
    end
    
    bool = false;
    missing = {};

    thisdir = fileparts(mfilename('fullpath'));
    
    % Check if ../matnwb/nwbRead.m exists
    if ~isfile(fullfile(thisdir, '..', 'matnwb', 'nwbRead.m'))
        % If not found, core and all extensions are missing
        missing = [{'matnwb'}, requiredExtensions];
        return;
    end
    
    % Make sure the core matnwb is ok
    try
        versionInfo = ver("matnwb");
        if isempty(versionInfo)
            missing = [{'matnwb'}, requiredExtensions];
            return;
        end
    catch
        missing = [{'matnwb'}, requiredExtensions];
        return;
    end

    % Check for each required extension
    for i = 1:length(requiredExtensions)
        % Check for the extension Version.m file in ../matnwb/+types/+<extension>/
        extName = requiredExtensions{i};
        extPath = fullfile(thisdir, '..', 'matnwb', '+types', ['+' strrep(extName, '-', '_')], 'Version.m');
        if ~isfile(extPath)
            missing{end+1} = extName; %#ok<AGROW>
        end
    end
    if isempty(missing)
        bool = true;
        ensurepath(); % Ensure that, if available, matnwb is on the MATLAB path
    end
end

function ensurepath()
    % Ensure that the core matnwb is added to MATLAB path
    thisdir = fileparts(mfilename('fullpath'));
    thisdirparent = fileparts(thisdir);
    corePath = fullfile(thisdirparent, 'matnwb');
    if ~contains(path, corePath)
        addpath(corePath);
    end
end