function f = populationPlacePref(normalizedPopulationData, populationSummaryData, kvargs)
    %%POPULATIONPLACEPREF Given a table of normalized place preference data, generate
    % summary figures for population level place preference behavior.
    %
    %   INPUTS:
    %       normalizedPopulationData - A table of normalized place preference data,
    %           generated by population.stats.normalizeSummaryTable
    %       populationSummaryData (optional) - A table of population summary data,
    %           generated by population.stats.populationSummary
    %           If provided, will show additional export options in the figure menu.
    %
    %   Name-Value Pair Arguments:
    %       'MainApp' - handle to the main PlacePrefDataGUI_main app (for additional configs + syncing)
    %
    %
    %   OUTPUTS:
    %       f - figure handle of the generated figure
    %
    %   See also: population.stats.normalizeSummaryTable, population.stats.populationSummary

    arguments
        normalizedPopulationData table
        populationSummaryData table = table();

        kvargs.MainApp {mustBeAOrEmpty(kvargs.MainApp, 'PlacePrefDataGUI_main')} = [];
    end

    requiredColumns = {'Strain', 'Sex', 'Genotype', 'Age', 'Stimulus Task', 'Animal UID by Stim Combo'};
    missing = setdiff(requiredColumns, normalizedPopulationData.Properties.VariableNames, 'stable');
    if ~isempty(missing)
        error('The provided normalizedPopulationData is missing required columns: { ''%s'' }', strjoin(missing, ''', '''));
    end
    % Make sure there are at least 2 columns that start with "Norm "
    normCols = startsWith(normalizedPopulationData.Properties.VariableNames, "Norm ");
    if sum(normCols) < 2
        error('The provided normalizedPopulationData must contain at least 2 columns that start with "Norm ".');
    end

    genotypeCombo = strcat(cellstr(normalizedPopulationData.("Strain")), " - ", cellstr(normalizedPopulationData.("Sex")), " - ", cellstr(normalizedPopulationData.("Genotype")));
    normalizedPopulationData = addvars(normalizedPopulationData, categorical(genotypeCombo), 'NewVariableNames', "Genotype Group");
    allLabels = repmat("All", height(normalizedPopulationData), 1);
    normalizedPopulationData = addvars(normalizedPopulationData, categorical(allLabels), 'NewVariableNames', "All"); % Easier if want to group by all later

    uniqueStimTasks = unique(normalizedPopulationData.("Stimulus Task"));

    screen = get(0, 'ScreenSize');
    w = screen(3) * 0.8; px = (screen(3) - w) / 2;
    h = screen(4) * 0.65; py = (screen(4) - h) / 2;
    f = figure('Position', [px, py, w, h], 'Color', 'w', 'Name', 'Population Place Preferences', 'NumberTitle', 'off', 'ToolBar', 'none', 'MenuBar', 'figure');

    tgroup = uitabgroup(f, 'Position', [0 0 1 1]);

    %% Summary Tab: Group by All, Sex, Strain, and Genotype simply showing Speaker Side Preferences
    summaryTab = uitab(tgroup, 'Title', 'Summary by Speaker/Side Preferences', 'BackgroundColor', 'w');
    nrow = 2; ncol = 3;
    sumTL = tiledlayout(summaryTab, nrow, ncol, 'TileSpacing', 'Compact', 'Padding', 'Compact');

    ax = nexttile(sumTL, 1, [1 1]);
    [meanData, stdData, groups] = getGroupedData(normalizedPopulationData, "All", ["Norm Matched Left Speaker", "Norm Matched Right Speaker"]);
    plotGroupedBar(ax, meanData, stdData, groups, "Animal - Physical Speaker/Side Preferences", ["Left Speaker", "Right Speaker"]);

    ax = nexttile(sumTL, ncol * 1 + 1, [1 1]);
    [meanData, stdData, groups] = getGroupedData(normalizedPopulationData, "Sex", ["Norm Matched Left Speaker", "Norm Matched Right Speaker"]);
    plotGroupedBar(ax, meanData, stdData, groups, "Animal - Physical Speaker/Side Preferences by Sex", ["Left Speaker", "Right Speaker"]);

    ax = nexttile(sumTL, 2, [1 2]);
    [meanData, stdData, groups] = getGroupedData(normalizedPopulationData, "Strain", ["Norm Matched Left Speaker", "Norm Matched Right Speaker"]);
    plotGroupedBar(ax, meanData, stdData, groups, "Animal - Physical Speaker/Side Preferences by Strain", ["Left Speaker", "Right Speaker"]);

    ax = nexttile(sumTL, ncol * 1 + 2, [1 2]);
    [meanData, stdData, groups] = getGroupedData(normalizedPopulationData, "Genotype", ["Norm Matched Left Speaker", "Norm Matched Right Speaker"]);
    plotGroupedBar(ax, meanData, stdData, groups, "Animal - Physical Speaker/Side Preferences by Genotype", ["Left Speaker", "Right Speaker"]);


    %% Each Stimulus Task
    for i = 1:length(uniqueStimTasks)
        stimTaskStr = uniqueStimTasks(i);
        stimTasks = strtrim(split(cellstr(stimTaskStr), '||'));
        stimTasksNorm = strcat("Norm ", stimTasks);

        stimdata = normalizedPopulationData(ismember(normalizedPopulationData.("Stimulus Task"), stimTaskStr), :);

        % If stimtask includes "Normal", bring that task to the front of the list
        normIdx = find(contains(stimTasks, "Normal", 'IgnoreCase', true), 1);
        if ~isempty(normIdx) && normIdx ~= 1
            stimTasks = [stimTasks(normIdx); stimTasks(setdiff(1:end, normIdx))];
            stimTasksNorm = strcat("Norm ", stimTasks);
        end
        stimTaskStrFormatted = strjoin(stimTasks, " vs. ");

        thistab = uitab(tgroup, 'Title', stimTaskStrFormatted, 'BackgroundColor', 'w');

        ax = axes(thistab); %#ok<LAXES>
        [meanData, stdData, groups] = getGroupedData(stimdata, "Genotype Group", stimTasksNorm);
        plotGroupedBar(ax, meanData, stdData, groups, sprintf("%s - Place Preferences", stimTaskStrFormatted), stimTasks);
    end


    hFileMenu = findall(f, 'tag', 'figMenuFile');
    hMruMenu = uimenu('Label', 'Export Data...', 'Parent', hFileMenu);
    hAllMenuItems = allchild(hFileMenu);
    hExportSetupMenu = findall(hFileMenu, 'Tag', 'figMenuFileExportSetup');
    if isempty(hExportSetupMenu)
        insertPos = 0;
    else
        insertPos = find(hAllMenuItems == hExportSetupMenu) - 1;
    end
    set(hFileMenu, 'Children',fliplr([hAllMenuItems(1:insertPos); hMruMenu; hAllMenuItems(insertPos+1:end)]));

    if isempty(kvargs.MainApp) || ~isvalid(kvargs.MainApp) || ~isfolder(kvargs.MainApp.lastDirPath)
        kvargs.MainApp.lastDirPath = pwd; % treat this as a struct
    end

    if ~isempty(populationSummaryData)
        uimenu(hMruMenu, 'Label', 'Population Summary Data', 'Callback', {@exportVar, populationSummaryData, 'PopulationSummaryData', 'PopulationSummaryData.mat', 'Export Population Summary Data as...', kvargs.MainApp});
    end
    uimenu(hMruMenu, 'Label', 'Normalized Place Preferences Data', 'Callback', {@exportVar, normalizedPopulationData, 'NormalizedPopulationData', 'NormalizedPopulationData.mat', 'Export Normalized Population Data as...', kvargs.MainApp});
end


function mustBeAOrEmpty(x, className)
    if ~isempty(x) && ~isa(x, className)
        error('Input must be of class %s or empty.', className);
    end
end

function mustBeOneOfAOrEmpty(x, classNames)
    if ~isempty(x) && ~any(cellfun(@(c) isa(x, c), classNames))
        error('Input must be one of the classes: %s or empty.', strjoin(classNames, ', '));
    end
end


function [meanData, stdData, groups] = getGroupedData(datatable, groupByVar, dependentVars)
    % Get the mean and std of dependentVars grouped by groupByVar
    stats = groupsummary(datatable, groupByVar, ["mean","std"], dependentVars);
    groupLabels = string(stats.(groupByVar)');
    groupN = string(stats.("GroupCount")');
    meanA = stats.("mean_" + dependentVars(1))';
    meanB = stats.("mean_" + dependentVars(2))';
    stdA = stats.("std_" + dependentVars(1))';
    stdB = stats.("std_" + dependentVars(2))';
    meanData = [meanA; meanB]; stdData = [stdA; stdB];
    % Join groups + groupN, matching elements
    groups = strcat(groupLabels, " (N = ", groupN, ")");
end


function ax = plotGroupedBar(ax, meanData, stdData, groups, titleStr, legendStr)
    % Workaround to make sure bar() group the data correctly when meanData is square
    % Repeat the groups to match the number of columns in meanData
    % Weirdly enough, errorbar() seems to work correctly regardless, so no need to use meanDataT there
    if size(meanData,1) == size(meanData,2)
        groups = repmat(groups', 1, size(meanData,2));
        meanDataT = meanData';
    else
        meanDataT = meanData;
    end

    
    b = bar(ax, categorical(groups), meanDataT, "Interpreter", "none");
    % Plot error bars
    hold on;
    [ngroups,nbars] = size(meanData');
    x = nan(nbars, ngroups);
    for i = 1:nbars
        x(i,:) = b(i).XEndPoints;
    end
    errorbar(x, meanData, stdData,'k','linestyle','none');
    hold off;

    ax.YLabel.String = "% of Time Spent in Zone when Zone is Active";
    ax.TickLabelInterpreter = "none";
    ax.XLabel.Interpreter = "none";
    ax.Title.String = titleStr;
    legend(ax, legendStr, "Location", "northwest");
end



function exportVar(hObject, eventData, variable, variableName, defaultFileName, title, mainapphandle)
    arguments
        hObject
        eventData
        variable
        variableName {mustBeValidVariableName}
        defaultFileName {mustBeTextScalar} = sprintf("%s.mat", variableName)
        title {mustBeTextScalar} = sprintf('Save ''%s'' as...', variableName)
        mainapphandle {mustBeOneOfAOrEmpty(mainapphandle, {'PlacePrefDataGUI_main', 'struct'})} = [];
    end

    defaultDir = pwd;
    if ~isempty(mainapphandle) && isvalid(mainapphandle)
        defaultDir = mainapphandle.lastDirPath;
    end

    [fileName, filePath] = uiputfile({'*.mat', 'MAT-files (*.mat)'}, title, fullfile(defaultDir, defaultFileName));
    if isequal(fileName, 0) || isequal(filePath, 0)
        return;
    end

    s = struct();
    s.(variableName) = variable;

    % Save the variable
    fullPath = fullfile(filePath, fileName);
    save(fullPath, '-struct', 's');

    if ~isempty(mainapphandle) && isvalid(mainapphandle)
        mainapphandle.lastDirPath = filePath;
    end
end