function c = strainColorMap(strain)
    %%STRAINCOLORMAP Returns a color associated with a given strain name.

    colors = dictionary( ...
        "C57BL/6J", "#34c06f",...
        "CBA/J", "#c2ad93",...
        "CBA/CaJ", "#e7768e",...
        "Shank3B", "#e48d46",...
        "Cntnap2", "#9e4fc0",...
        "Mecp2", "#4f81bd"...
    );

    allKeys = keys(colors);
    idx = find(strcmpi(strain, allKeys), 1);
    if ~isempty(idx)
        c = colors(allKeys{idx});
        c = validatecolor(c);
    else
        error('No color defined for strain: %s', strain);
    end
end