function errstr = buildmissinguvhelpererror(thisdir)
    errstr = sprintf([ ...
        '+uv helper namespace is not installed or not on the MATLAB path.\n' ...
        'Searched for helper roots relative to %s in ./ ; ../ ; ../../ ; ../../lib/ ; ../../../lib/.\n' ...
        'If +io/+sleap is installed as part of a package, make sure you also download/install the full package together with the +uv helper library.' ...
    ], thisdir);
end
