function ok = isuvnamespacemissingerror(ME)
    if isempty(ME)
        ok = false;
        return;
    end
    ok = strcmp(ME.identifier, 'MATLAB:UndefinedFunction') || ...
        contains(ME.message, 'Undefined function or variable ''uv''') || ...
        contains(ME.message, 'Undefined function or variable ''uv.install''') || ...
        contains(ME.message, 'Undefined function ''uv.install''') || ...
        contains(ME.message, 'Unable to resolve the name ''uv.install''');
end
