function outputpath = L1export(projectFolder, trials, kvargs)
    arguments
        projectFolder {mustBeTextScalar, mustBeFolder}
        trials struct {mustBeTrialInfoStructs} % A struct array of trialInfo, generated by ui.trackingPlatforms.TrackingProvider.filterTrials(projectFolder)

        kvargs.outputFolder {validator.mustBeValidFolderpath} = fullfile(projectFolder, 'L1 Export')
    end

    projectFolder = char(projectFolder);

    nonmultiarenatrials = trials(~[trials.multipleArena]);

    if isempty(nonmultiarenatrials)
        warning('dracc:io:L1export:NoValidTrials', 'No split/single arena trials found. No L1 export will be generated. Before running this export, make sure to pre-process the trials and split any multi-arena trials into single arena trials.');
    end

    % All non-multi-arena trials .data files also need to have a corresponding <base name> - [hash].mat file next to them that contains the stim-aligned data + associated metadata
    missingMatFiles = [];
    for i = 1:numel(nonmultiarenatrials)
        trial = nonmultiarenatrials(i);
        dataFile = trial.data;
        [dataDir, dataBaseName, ~] = fileparts(dataFile);
        hashMatFile = "";
        for file = dir(fullfile(dataDir, [dataBaseName, ' - *.mat']))
            if startsWith(string(file.name), strcat(dataBaseName, ' - ')) && endsWith(string(file.name), ".mat")
                hashMatFile = fullfile(dataDir, file.name);
                break;
            end
        end
        if isempty(hashMatFile) || ~isfile(hashMatFile)
            missingMatFiles = [missingMatFiles; string(dataFile)]; %#ok<AGROW>
        end
    end
    if ~isempty(missingMatFiles)
        error('dracc:io:L1export:MissingAlignedMatFiles', 'The aligned .mat files corresponding to the data files of the non-multi-arena trials are missing. These .mat files are required for the L1 export. Please make sure they are generated and placed next to their corresponding data files before running this export.\n%s', strjoin(missingMatFiles, '\n'));
    end

    % Similarly, the .media files also need to have a corresponding <base name>.ref.json file.
    % Auto-migrate legacy midpoint/midline CSV files before validating.
    missingRefFiles = [];
    for i = 1:numel(nonmultiarenatrials)
        trial = nonmultiarenatrials(i);
        mediaFile = trial.media;
        [mediaDir, mediaBaseName, ~] = fileparts(mediaFile);
        graphics.migrateLegacyCSVRefs2JSON(mediaDir);
        refJsonFile = fullfile(mediaDir, strcat(mediaBaseName, '.ref.json'));
        if ~isfile(refJsonFile)
            missingRefFiles = [missingRefFiles; string(mediaFile)]; %#ok<AGROW>
        end
    end
    if ~isempty(missingRefFiles)
        error('dracc:io:L1export:MissingReferenceJsonFiles', 'The reference .ref.json files corresponding to the media files of the non-multi-arena trials are missing. These files are required for the L1 export. Please make sure they are generated and placed next to their corresponding media files before running this export.\n%s', strjoin(missingRefFiles, '\n'));
    end


    [~, projectFolderName] = fileparts(projectFolder);

    % Zip the outputdir = fullfile(outputdir, projectFolderName) into projectFolderName_L1.zip in kvargs.outputFolder
    zipFilePath = fullfile(kvargs.outputFolder, strcat(projectFolderName, '_L1.zip'));
    if isfile(zipFilePath)
        warning('dracc:io:L1export:ZipFileExists', 'The zip file "%s" already exists. To avoid overwriting, please manually delete the existing file first.', zipFilePath);
        return;
    end

    outputdir = char(kvargs.outputFolder);
    outputdir = fullfile(outputdir, projectFolderName);
    if ~exist(outputdir, 'dir')
        mkdir(outputdir);
    end

    % Copy all trials.media files into outputdir/Media Files/; and all trials.data files into outputdir/Export Files/;
    mediaOutputDir = fullfile(outputdir, 'Media Files');
    dataOutputDir = fullfile(outputdir, 'Export Files');
    if ~exist(mediaOutputDir, 'dir')
        mkdir(mediaOutputDir);
    end
    if ~exist(dataOutputDir, 'dir')
        mkdir(dataOutputDir);
    end

    for i = 1:numel(nonmultiarenatrials)
        trial = nonmultiarenatrials(i);
        copyfile(trial.media, mediaOutputDir);
        copyfile(trial.data, dataOutputDir);
        % Also copy the corresponding aligned .mat file and reference .ref.json file
        [dataDir, dataBaseName, ~] = fileparts(trial.data);
        hashMatFile = "";
        for file = dir(fullfile(dataDir, [dataBaseName, ' - *.mat']))
            if startsWith(string(file.name), strcat(dataBaseName, ' - ')) && endsWith(string(file.name), ".mat")
                hashMatFile = fullfile(dataDir, file.name);
                break;
            end
        end
        if ~isempty(hashMatFile)
            copyfile(hashMatFile, dataOutputDir);
        end

        [mediaDir, mediaBaseName, ~] = fileparts(trial.media);
        graphics.migrateLegacyCSVRefs2JSON(mediaDir);
        refJsonFile = fullfile(mediaDir, strcat(mediaBaseName, '.ref.json'));
        if isfile(refJsonFile)
            copyfile(refJsonFile, mediaOutputDir);
        end
    end


    % TODO: Maybe add metadata export for this data set as well for redundancy!


    % Zip and remove temp dir
    zip(zipFilePath, outputdir, outputdir);
    rmdir(outputdir, 's');
    outputpath = zipFilePath;
end


function mustBeTrialInfoStructs(trials)
    % Validate that trials is a struct array with the required fields\
    %       trialInfo - A struct array containing the filtered trials with fields:
    %                'media' - path to the media file (in Media Files subfolder)
    %                'data'  - path to the data file (in Export Files subfolder)
    %                'trialNumeric' - last numeric part of the trial name
    %                'multipleArena' - boolean indicating if the trial XLSX export contains multiple arenas
    %                'arena' - name of the arena, or '!multiple!' if multiple arenas
    
    requiredFields = {'media', 'data', 'trialNumeric', 'multipleArena', 'arena'};
    for i = 1:numel(trials)
        for j = 1:numel(requiredFields)
            if ~isfield(trials(i), requiredFields{j})
                error('Each trialInfo struct must contain the field "%s".', requiredFields{j});
            end
        end
    end
end