function outputpath = L1export(projectFolder, trials, kvargs)
    arguments
        projectFolder {mustBeTextScalar, mustBeFolder}
        trials struct {mustBeTrialInfoStructs} % A struct array of trialInfo, generated by ui.trackingPlatforms.TrackingProvider.filterTrials(projectFolder)

        kvargs.TrackingProvider (1,1) ui.trackingPlatforms.TrackingProvider
        kvargs.outputFolder {validator.mustBeValidFolderpath} = fullfile(projectFolder, 'L1 Export')
    end

    kvargs.TrackingProvider.requireCapability("L1export");
    projectFolder = char(utils.path.canonicalize(projectFolder));

    nonmultiarenatrials = trials(~[trials.multipleArena]);

    if isempty(nonmultiarenatrials)
        warning('dracc:io:L1export:NoValidTrials', 'No split/single arena trials found. No L1 export will be generated. Before running this export, make sure to pre-process the trials and split any multi-arena trials into single arena trials.');
    end

    % Resolve all trial paths against the project root. The relative paths are
    % retained so the export preserves the source project layout.
    mediaFiles = strings(numel(nonmultiarenatrials), 1);
    mediaRelativePaths = strings(numel(nonmultiarenatrials), 1);
    dataFiles = strings(numel(nonmultiarenatrials), 1);
    dataRelativePaths = strings(numel(nonmultiarenatrials), 1);
    for i = 1:numel(nonmultiarenatrials)
        [mediaFiles(i), mediaRelativePaths(i)] = resolveProjectFile( ...
            nonmultiarenatrials(i).media, projectFolder, 'media');
        [dataFiles(i), dataRelativePaths(i)] = resolveProjectFile( ...
            nonmultiarenatrials(i).data, projectFolder, 'data');
    end

    % All non-multi-arena trials .data files also need to have a corresponding provider-labeled aligned MAT file next to them.
    missingMatFiles = [];
    alignedMatFiles = strings(numel(nonmultiarenatrials), 1);
    alignedRelativePaths = strings(numel(nonmultiarenatrials), 1);
    for i = 1:numel(nonmultiarenatrials)
        [dataDir, dataBaseName, ~] = fileparts(dataFiles(i));
        alignedFile = findAlignedCacheFile(dataDir, dataBaseName, kvargs.TrackingProvider.platform, dataFiles(i));
        alignedMatFiles(i) = alignedFile;
        if strlength(alignedMatFiles(i)) == 0
            missingMatFiles = [missingMatFiles; dataFiles(i)]; %#ok<AGROW>
        else
            [alignedMatFiles(i), alignedRelativePaths(i)] = resolveProjectFile( ...
                alignedMatFiles(i), projectFolder, 'aligned MAT');
        end
    end
    if ~isempty(missingMatFiles)
        error('dracc:io:L1export:MissingAlignedMatFiles', 'The aligned .mat files corresponding to the data files of the non-multi-arena trials are missing. These .mat files are required for the L1 export. Please make sure they are generated and placed next to their corresponding data files before running this export.\n%s', strjoin(missingMatFiles, '\n'));
    end

    % Similarly, the .media files also need to have a corresponding <base name>.ref.json and a <base name>.ref.arenagrid.mat file.
    % Auto-migrate legacy midpoint/midline CSV files before validating.
    missingRefFiles = [];
    missingArenaGridFiles = [];
    refJsonFiles = strings(numel(nonmultiarenatrials), 1);
    refJsonRelativePaths = strings(numel(nonmultiarenatrials), 1);
    arenaGridMatFiles = strings(numel(nonmultiarenatrials), 1);
    arenaGridRelativePaths = strings(numel(nonmultiarenatrials), 1);
    for i = 1:numel(nonmultiarenatrials)
        [mediaDir, mediaBaseName, ~] = fileparts(mediaFiles(i));
        graphics.migrateLegacyCSVRefs2JSON(mediaDir);
        refJsonFile = string(fullfile(mediaDir, strcat(mediaBaseName, '.ref.json')));
        arenaGridMatFile = string(fullfile(mediaDir, strcat(mediaBaseName, '.ref.arenagrid.mat')));
        if ~isfile(refJsonFile)
            missingRefFiles = [missingRefFiles; mediaFiles(i)]; %#ok<AGROW>
        else
            [refJsonFiles(i), refJsonRelativePaths(i)] = resolveProjectFile( ...
                refJsonFile, projectFolder, 'reference JSON');
        end
        if ~isfile(arenaGridMatFile)
            missingArenaGridFiles = [missingArenaGridFiles; mediaFiles(i)]; %#ok<AGROW>
        else
            [arenaGridMatFiles(i), arenaGridRelativePaths(i)] = resolveProjectFile( ...
                arenaGridMatFile, projectFolder, 'arena grid MAT');
        end
    end
    if ~isempty(missingRefFiles)
        error('dracc:io:L1export:MissingReferenceJsonFiles', 'The reference .ref.json files corresponding to the media files of the non-multi-arena trials are missing. These files are required for the L1 export. Please make sure they are generated and placed next to their corresponding media files before running this export.\n%s', strjoin(missingRefFiles, '\n'));
    end
    if ~isempty(missingArenaGridFiles)
        error('dracc:io:L1export:MissingArenaGridFiles', 'The arena grid .ref.arenagrid.mat files corresponding to the media files of the non-multi-arena trials are missing. These files are required for the L1 export. Please make sure they are generated and placed next to their corresponding media files before running this export.\n%s', strjoin(missingArenaGridFiles, '\n'));
    end


    [~, projectFolderName] = fileparts(projectFolder);

    % Zip the outputdir = fullfile(outputdir, projectFolderName) into projectFolderName_L1.zip in kvargs.outputFolder
    zipFilePath = fullfile(kvargs.outputFolder, strcat(projectFolderName, '_L1.zip'));
    if isfile(zipFilePath)
        warning('dracc:io:L1export:ZipFileExists', 'The zip file "%s" already exists. To avoid overwriting, please manually delete the existing file first.', zipFilePath);
        return;
    end

    outputdir = char(kvargs.outputFolder);
    outputdir = fullfile(outputdir, projectFolderName);
    if ~exist(outputdir, 'dir')
        mkdir(outputdir);
    end

    % Copy every source file to its project-relative path below outputdir.
    for i = 1:numel(nonmultiarenatrials)
        copyRelativeFile(mediaFiles(i), mediaRelativePaths(i), outputdir);
        copyRelativeFile(dataFiles(i), dataRelativePaths(i), outputdir);

        % Also copy the corresponding aligned MAT and reference files.
        if strlength(alignedMatFiles(i)) > 0
            copyRelativeFile(alignedMatFiles(i), alignedRelativePaths(i), outputdir);
        end

        if strlength(refJsonFiles(i)) > 0
            copyRelativeFile(refJsonFiles(i), refJsonRelativePaths(i), outputdir);
        end

        if strlength(arenaGridMatFiles(i)) > 0
            copyRelativeFile(arenaGridMatFiles(i), arenaGridRelativePaths(i), outputdir);
        end
    end


    % TODO: Maybe add metadata export for this data set as well for redundancy!
    % Alternatively, manually copy the metadata from the MasterMetadata excel sheet to another sheet subset


    % Lastly, copy the TrackingProvider.userConfig.CONFIG_FILE runtime config to the outputdir, if it exists.
    % Rename as 'configs.runtime.yml'
    configFilePath = kvargs.TrackingProvider.userConfig.CONFIG_FILE;
    if isfile(configFilePath)
        outputConfigPath = fullfile(outputdir, 'configs.runtime.yml');
        [status,msg] = copyfile(configFilePath, outputConfigPath);
        if ~status
            error('dracc:io:L1export:ConfigCopyFailed', 'Failed to copy the runtime config file from "%s" to "%s":\n%s', configFilePath, outputConfigPath, getReport(msg));
        end
    else
        warning('dracc:io:L1export:MissingRuntimeConfig', 'The runtime config file "%s" does not exist. No runtime config will be included in the L1 export.', configFilePath);
    end


    % Zip and remove temp dir
    % fprintf('Creating L1 export zip file: \n\t%s\n\nThis will take a while...\n', zipFilePath);
    zip(zipFilePath, outputdir, outputdir);
    rmdir(outputdir, 's');
    outputpath = zipFilePath;
end

function [resolvedPath, relativePath] = resolveProjectFile(filePath, projectFolder, description)
    % Resolve a source file against projectFolder and return its safe relative path.
    filePath = string(filePath);
    projectFolder = string(projectFolder);
    description = string(description);

    if strlength(strtrim(filePath)) == 0
        error('dracc:io:L1export:MissingSourceFile', ...
            'The %s source path is empty.', description);
    end

    if ~utils.path.isAbsolute(filePath)
        filePath = string(fullfile(projectFolder, filePath));
    end

    if ~isfile(filePath)
        error('dracc:io:L1export:MissingSourceFile', ...
            'The %s source file does not exist: %s', description, filePath);
    end

    resolvedPath = string(utils.path.canonicalize(filePath));
    projectFolder = string(utils.path.canonicalize(projectFolder));
    projectPrefix = projectFolder;
    if ~endsWith(projectPrefix, string(filesep))
        projectPrefix = projectPrefix + string(filesep);
    end

    comparisonPath = resolvedPath;
    comparisonPrefix = projectPrefix;
    if ispc
        comparisonPath = lower(comparisonPath);
        comparisonPrefix = lower(comparisonPrefix);
    end

    if ~startsWith(comparisonPath, comparisonPrefix)
        error('dracc:io:L1export:SourceOutsideProject', ...
            'The %s source file must be inside projectFolder. File: %s; projectFolder: %s', ...
            description, resolvedPath, projectFolder);
    end

    relativePath = extractAfter(resolvedPath, strlength(projectPrefix));
end

function copyRelativeFile(sourceFile, relativePath, outputdir)
    destinationFile = fullfile(outputdir, relativePath);
    [destinationDir, ~, ~] = fileparts(destinationFile);
    if ~exist(destinationDir, 'dir')
        mkdir(destinationDir);
    end
    copyfile(sourceFile, destinationFile);
end

function alignedFile = findAlignedCacheFile(dataDir, dataBaseName, trackingPlatform, dataFile)
    alignedFile = "";
    alignedFiles = dir(fullfile(dataDir, '*.mat'));
    matchingFiles = strings(0, 1);
    for fileIdx = 1:numel(alignedFiles)
        cacheInfo = io.cache.parseAlignedCacheFileName(alignedFiles(fileIdx).name, ...
            ExpectedDataBaseName=dataBaseName, ...
            ExpectedTrackingPlatform=trackingPlatform);
        if cacheInfo.isProviderLabeled && ...
                strcmp(cacheInfo.dataBaseName, string(dataBaseName)) && ...
                strcmpi(cacheInfo.trackingPlatform, trackingPlatform)
            matchingFiles(end+1) = string(fullfile(alignedFiles(fileIdx).folder, alignedFiles(fileIdx).name)); %#ok<AGROW>
        end
    end

    if numel(matchingFiles) > 1
        error('dracc:io:L1export:AmbiguousAlignedMatFiles', ...
            'Multiple aligned MAT files for data file "%s" match tracking provider "%s":\n%s', ...
            dataFile, trackingPlatform, strjoin(matchingFiles, '\n'));
    end
    if ~isempty(matchingFiles) && isfile(matchingFiles(1))
        alignedFile = matchingFiles(1);
    end
end


function mustBeTrialInfoStructs(trials)
    % Validate that trials is a struct array with the required fields\
    %       trialInfo - A struct array containing the filtered trials with fields:
    %                'media' - path to the media file (in Media Files subfolder)
    %                'data'  - path to the data file (in Export Files subfolder)
    %                'trialNumeric' - last numeric part of the trial name
    %                'multipleArena' - boolean indicating if the trial XLSX export contains multiple arenas
    %                'arena' - name of the arena, or '!multiple!' if multiple arenas
    
    requiredFields = {'media', 'data', 'trialNumeric', 'multipleArena', 'arena'};
    for i = 1:numel(trials)
        for j = 1:numel(requiredFields)
            if ~isfield(trials(i), requiredFields{j})
                error('Each trialInfo struct must contain the field "%s".', requiredFields{j});
            end
        end
    end
end