# THIS IS THE CONFIGURATION FILE FOR THE HBOX (OpenField with Hallway) PLACE PREFERENCE SETUP.

preferences:

defaults:
  stimuli_directory: "../../Stimuli/playlists"
  master_metadata_table: "../../WUSMAC - Place Preferences - Master Metadata.xlsx"
  project_root: "../../ETHOVISION"
  tracking_platform: "EthoVision"

  nidaq_audioplayer_bin: #"%LOCALAPPDATA%/NI-DAQmxAudioPlayer/nidaq_audioplayer.exe"
  audio_metadata_extract_bin: #"./src/+io/+stimuli/metadata_extract.exe"

  xflip: false
  yflip: false
  distance2refmode: "line"
  arena_grid_mode: manual


arena_grid:
  # Number of vertices for the arena grid polygon when arena_grid_mode is set to "manual". In "auto" or "FOV" modes, n_vertices will always be 4.
  n_vertices: 4
  n_tiles: [100, 60] # Number of tiles along x and y dimensions, respectively. Default is [100, 100].
  score_x_gradient_function: "linear"
  score_x_gradient: [1, 0, -1]
  score_y_gradient_function: "linear"
  score_y_gradient: [0.4, 1, 0.4]


tracking_providers:
  EthoVision:
    # Default settings applied to all sub-categories unless overridden 
    coordsUnit: "cm"
    default_camera_imgwidth_fov_cm: 92
    default_camera_center_offset_px: [0, 0]
    default_zone_match_method: "startsWith"  # one of these: "exact", "startsWith", "endsWith", "contains"


    arena:
      # When using multiple arenas or different arena configs exist, specify them here
      # Just make sure the names match those used in EthoVision
      - name: "Arena 1"
        camera_imgwidth_fov_cm: 92
        camera_center_offset_px: [0, 0]
        zone:
          left: Left
          right: Right
        zone_match_method: "startsWith"
        hidden_zones_assignment: # optional: If there are any hidden zones that should be treated as part of left/right zones, specify them here
          - name: "TopLeft Hidden" # name of the hidden zone in EthoVision
            assign_to: "left" # assign to either "left" or "right"
          - name: "BottomLeft Hidden"
            assign_to: "left"
          - name: "TopRight Hidden"
            assign_to: "right"
          - name: "BottomRight Hidden"
            assign_to: "right"

      - name: "Lily Booth"
        camera_imgwidth_fov_cm: 92.25
        camera_center_offset_px: [962, 0]
        zone:
          left: Left Speaker 1
          right: Right Speaker 1
        zone_match_method: "exact"
        hidden_zones_assignment:
          - name: "TopLeft Hidden 1"
            assign_to: "left"
          - name: "BottomLeft Hidden 1"
            assign_to: "left"
          - name: "TopRight Hidden 1"
            assign_to: "right"
          - name: "BottomRight Hidden 1"
            assign_to: "right"
        neutral_zones:
          - name: "Hallway 1"
      
      - name: "Rain Booth"
        camera_imgwidth_fov_cm: 92.25
        camera_center_offset_px: [-960, 0]
        zone:
          left: Left Speaker 2
          right: Right Speaker 2
        zone_match_method: "exact"
        hidden_zones_assignment:
          - name: "TopLeft Hidden 2"
            assign_to: "left"
          - name: "BottomLeft Hidden 2"
            assign_to: "left"
          - name: "TopRight Hidden 2"
            assign_to: "right"
          - name: "BottomRight Hidden 2"
            assign_to: "right"
        neutral_zones:
          - name: "Hallway 2"


  DeepLabCut:
    config_file: "../../DLCDetectionModel/config.yaml"