%%JOINSTDTABLEBYSTIM Join 2 standardized center point tables by matching stimuli based on 'Trial time' and 'Stimulus name'
%
% WARNING: CHECK THIS FUNCTION FILE AND READ ITS DOCUMENTATION CAREFULLY FOR THE USE CASES IT IS DESIGNED FOR BEFORE USING IT.
%
%       joinedStdTable = population.temp.joinStdTableByStim(stdTableA, stdTableB)
%
%   Inputs:
%       stdTableA - A standardized stimtable struct generated by population.stats.populationPositionOverTime that is similar to stdTableB with different lengths
%       stdTableB - A standardized stimtable struct generated by population.stats.populationPositionOverTime that is similar to stdTableA with different lengths
%
%       (This is the struct format output from population.stats.populationPositionOverTime(i))
%        Both tables.stimuliSorted must be the same between A and B
%        Both tables.centerpointData must have 'Trial time' and 'Stimulus name' columns, must share the same sampling rate for 'Trial time', and must have the same set of columns (other than 'Trial time' and 'Stimulus name').
%
%   Outputs:
%       joinedStdTable - A joined standardized table with table.centerpointData's N-rows equal to either A or B, whichever is longer, with rows matched by 'Trial time' and/or 'Stimulus name' for the least amount of inserted NaN rows. The columns are joined into sub-tables sharing the same original headers from A to B, with rows filled with NaNs where no match is found for that stimulus. Other fields in the struct (like metadata) are either copied if both are the same (like stimuliSorted), or merged in order of [A, B] if they are different (like animalMetadata or stimfileName).
%           For the intended use case, where B is a superset of A (i.e. B includes A plus some extra stimuli blocks somewhere in the trial, typically at the end), the resulting centerpointData table will have the same number of rows as B, with rows from A matched to B by 'Trial time' and 'Stimulus name', and NaN rows inserted in A where no match is found.
%
%  See also: population.stats.populationPositionOverTime
%
%
% BACKGROUND and USE CASE:
% When creating stimuli using the playlist generator included in the NI-DAQmx Media Player (https://github.com/codynhanpham/nidaq_audioplayer)
% That is, create a YML-formatted playlist WITH A SET SEED, then generate the FLAC stimuli from that playlist
% all randomizations will be consistent in the same order as long as the same seed is used.
% For example, you created a playlist with seed 12345, repeating [track1.wav, pause[5000|10000]ms] 10 times then append [track2.wav] at the end to produce output1.flac
% Then, you create another playlist with the same seed 12345, repeating [track1.wav, pause[5000|10000]ms] 15 times then append [track2.wav] at the end to produce output2.flac
% The first 10 repetitions of output2.flac and output1.flac will be the same, even though pause[5000|10000]ms will generate a random pause duration each time between 5000ms and 10000ms.
% That is because the randomization is designed to be deterministic based on the seed. As long as the randomization action are performed in the same order, the same sequence will be generated.
%
% This function will greedily match the stimuli of 2 different standardizedTables.centerpointData (generated by population.stats.populationPositionOverTime) tables by their 'Trial time' and 'Stimulus name' columns from time 0s to the end of the trial, matching the stimuli in the order they appear, filling in NaNs where no match is found.
% Refer back to the example above, this will match the first 10 stimuli of output2.flac to output1.flac, fill in NaNs for the remaining 5 stimuli of output2.flac that have no match in output1.flac, and continue to match the remaining matching stimuli by order.
%
% In short, think of this function similar to Git merging 2 files where one of them is a superset (with added rows) of the other file, and we want to align the rows of the superset file to the subset file by matching on 'Trial time' and 'Stimulus name'.
%
%
% WHY?
% During testing, sometimes we want to check the effect of different stimulus lengths on animal behavior.
% Some stimuli playlists contains shorter or longer versions of the same [stimuli+ISI] segment, only differing in the number of repetitions of those segments.
% This results in different number of stimuli per trial, thus different lengths of standardized center point tables.
% This function allows us to align those different length standardized center point tables by matching the stimuli based on 'Trial time' and 'Stimulus name', so that we can compare animal behavior across different stimulus lengths.




function joinedStdTable = joinStdTableByStim(stdTableA, stdTableB)


    arguments
        stdTableA struct
        stdTableB struct
    end

    % Validate other fields in the struct
    requiredFields = {'stimfileName', 'stimuliSorted', 'animalMetadata', 'centerpointData'};
    missingA = setdiff(requiredFields, fieldnames(stdTableA), 'stable');
    missingB = setdiff(requiredFields, fieldnames(stdTableB), 'stable');
    if ~isempty(missingA)
        error('The provided stdTableA is missing required fields: { ''%s'' }. Make sure that it was generated by population.stats.populationPositionOverTime or of similar format.', strjoin(missingA, ''', '''));
    end
    if ~isempty(missingB)
        error('The provided stdTableB is missing required fields: { ''%s'' }. Make sure that it was generated by population.stats.populationPositionOverTime or of similar format.', strjoin(missingB, ''', '''));
    end


    % stimuliSorted must be the same
    if ~isequal(stdTableA.stimuliSorted, stdTableB.stimuliSorted)
        error('The provided stdTableA and stdTableB must have the same stimuliSorted field.');
    end

    stdCenterPointTableA = stdTableA.centerpointData;
    stdCenterPointTableB = stdTableB.centerpointData;

    % A and B must have 'Trial time' and 'Stimulus name' columns, list of columns must be the same (other than 'Trial time' and 'Stimulus name')
    requiredColumns = {'Trial time', 'Stimulus name'};
    missingA = setdiff(requiredColumns, stdCenterPointTableA.Properties.VariableNames, 'stable');
    missingB = setdiff(requiredColumns, stdCenterPointTableB.Properties.VariableNames, 'stable');
    if ~isempty(missingA)
        error('The provided stdCenterPointTableA is missing required columns: { ''%s'' }', strjoin(missingA, ''', '''));
    end
    if ~isempty(missingB)
        error('The provided stdCenterPointTableB is missing required columns: { ''%s'' }', strjoin(missingB, ''', '''));
    end
    colsA = setdiff(stdCenterPointTableA.Properties.VariableNames, requiredColumns, 'stable');
    colsB = setdiff(stdCenterPointTableB.Properties.VariableNames, requiredColumns, 'stable');
    if ~isequal(sort(colsA), sort(colsB))
        error('The provided stdCenterPointTableA and stdCenterPointTableB must have the same set of columns (other than ''Trial time'' and ''Stimulus name'').');
    end
    % Both tables must have the same sampling rate for 'Trial time'
    % Check the difference between consecutive 'Trial time' values
    % Since they are standardized tables, the difference should be constant
    dtA = unique(round(diff(stdCenterPointTableA.('Trial time')), 10)); % some funny floating point precision issues, round to 10 decimal places
    dtB = unique(round(diff(stdCenterPointTableB.('Trial time')), 10)); % some funny floating point precision issues, round to 10 decimal places
    if ~isequal(dtA, dtB)
        error('The provided stdCenterPointTableA and stdCenterPointTableB must have the same sampling rate for ''Trial time''.');
    end

    joinedStdTable = struct();
    joinedStdTable.stimfileName = {stdTableA.stimfileName; stdTableB.stimfileName};
    joinedStdTable.stimuliSorted = stdTableA.stimuliSorted;
    
    % Join Animal Metadata by add keys from A first, then B
    % The metadata here is keyed by the corresponding animal centerPointData table,
    % so there should be no overlapping keys
    joinedStdTable.animalMetadata = stdTableA.animalMetadata;
    keysA = keys(stdTableA.animalMetadata);
    keysB = keys(stdTableB.animalMetadata);
    if ~isempty(intersect(keysA, keysB))
        error('The provided stdTableA (%s) and stdTableB (%s) have overlapping keys in animalMetadata. Cannot merge.', string(stdTableA.stimfileName), string(stdTableB.stimfileName));
    end
    for k = 1:length(keysB)
        key = keysB{k};
        joinedStdTable.animalMetadata(key) = stdTableB.animalMetadata(key);
    end

    %% Now join centerpointData tables by matching 'Trial time' and 'Stimulus name'
    
    % New table based on the longer of the 2 tables
    if height(stdCenterPointTableA) >= height(stdCenterPointTableB)
        baseTable = stdCenterPointTableA;
        matchTable = stdCenterPointTableB;
    else
        baseTable = stdCenterPointTableB;
        matchTable = stdCenterPointTableA;
    end

    % Find the matching continuous chunks between baseTable and matchTable
    % Note that the Trial time may not be exactly matching between the 2 tables due to floating point precision issues
    % Only check by using contiguous matching rows by 'Stimulus name', and assume that the 'Trial time' are aligned in the same order as they both share the same sampling rate
    
    % Determine which table is Base (Superset) for later ordering
    isBaseA = height(stdCenterPointTableA) >= height(stdCenterPointTableB);

    baseBlocks = getStimBlocks(baseTable);
    matchBlocks = getStimBlocks(matchTable);
    
    matchRowMap = nan(height(baseTable), 1);
    
    bIdx = 1; 
    mIdx = 1;
    
    while bIdx <= length(baseBlocks)
        bBlock = baseBlocks(bIdx);
        
        if mIdx <= length(matchBlocks)
            mBlock = matchBlocks(mIdx);
            
            if strcmp(bBlock.Name, mBlock.Name)
                % Map rows up to the minimum length of the two blocks
                lenToMap = min(bBlock.Count, mBlock.Count);
                
                baseIndices = bBlock.Start : (bBlock.Start + lenToMap - 1);
                matchIndices = mBlock.Start : (mBlock.Start + lenToMap - 1);
                
                matchRowMap(baseIndices) = matchIndices;
                
                mIdx = mIdx + 1;
            else
                % Mismatch: Treating Base block as insertion and skipping it
            end
        else
            % End of Match Table reached
        end
        
        bIdx = bIdx + 1;
    end
    
    %% Construct joined table columns
    
    dataCols = colsA; % or B, both are the same set of columns as validated earlier 
    
    % Create aligned columns from Match Table
    alignedMatchData = table();
    for i = 1:length(dataCols)
        colName = dataCols{i};
        colData = matchTable.(colName);
        
        % Initialize new column with NaNs/Missing
        if isnumeric(colData)
            newCol = nan(height(baseTable), size(colData, 2));
        elseif iscategorical(colData)
            newCol = repmat(categorical(nan), height(baseTable), 1);
        elseif isstring(colData)
            newCol = repmat(string(missing), height(baseTable), 1);
        else
            newCol = cell(height(baseTable), 1);
            [newCol{:}] = deal(missing);
        end
        
        % Fill matched rows
        validMask = ~isnan(matchRowMap);
        matchIndices = matchRowMap(validMask);
        newCol(validMask, :) = colData(matchIndices, :);
        
        alignedMatchData.(colName) = newCol;
    end
    
    % Rename columns and merge (A then B)
    if isBaseA
        % Base is A, Match is B
        partA = baseTable(:, dataCols);
        partB = alignedMatchData;
    else
        % Base is B, Match is A
        partA = alignedMatchData;
        partB = baseTable(:, dataCols);
    end
    
    % Merge A and B by horizontally concatenating the data within each column
    % The resulting table has the same columns as A/B, but each column's data is wider (N x (Ka+Kb))
    % Note that B must be after A in the concatenation to preserve the column order
    joinedCenterPointTable = baseTable(:, {'Trial time', 'Stimulus name'});
    for i = 1:length(dataCols)
        colName = dataCols{i};
        joinedCenterPointTable.(colName) = [partA.(colName), partB.(colName)];
    end
    
    joinedStdTable.centerpointData = joinedCenterPointTable;

end

function blocks = getStimBlocks(T)
    stims = string(T.('Stimulus name'));
    if isempty(stims)
        blocks = struct('Name', {}, 'Start', {}, 'End', {}, 'Count', {});
        return;
    end
    
    % Find indices where stimulus changes
    % Using 'diff' logic on strings. 
    % Note: stims(1:end-1) ~= stims(2:end) works for string arrays
    isChange = [true; stims(1:end-1) ~= stims(2:end)];
    startIdx = find(isChange);
    endIdx = [startIdx(2:end)-1; length(stims)];
    names = stims(startIdx);
    
    blocks = struct('Name', cellstr(names), 'Start', num2cell(startIdx), 'End', num2cell(endIdx), 'Count', num2cell(endIdx - startIdx + 1));
end