%%JOINSTDTABLEBYSTIM Join 2 standardized center point tables by matching stimuli based on 'Trial time' and 'Stimulus name'
%
% WARNING: CHECK THIS FUNCTION FILE AND READ ITS DOCUMENTATION CAREFULLY FOR THE USE CASES IT IS DESIGNED FOR BEFORE USING IT.
%
%       joinedStdTable = population.temp.joinStdTableByStim(stdTableA, stdTableB)
%
%   Inputs:
%       stdTableA - A standardized stimtable struct generated by population.stats.populationPositionOverTime that is similar to stdTableB with different lengths
%       stdTableB - A standardized stimtable struct generated by population.stats.populationPositionOverTime that is similar to stdTableA with different lengths
%
%       (This is the struct format output from population.stats.populationPositionOverTime(i))
%        Both tables.stimuliSorted must be the same between A and B.
%        Both tables must contain 'stimfileName', 'stimuliSorted',
%        'animalMetadata', and 'centerpointData'. The 'fps', 'px2cm', and
%        'bodyparts' fields are optional, but each must either be present in
%        both tables or absent from both tables.
%        Both centerpointData tables must have 'Trial time' and 'Stimulus name'
%        columns, must share the same sampling rate for 'Trial time', and must
%        have the same set of data columns other than the key columns.
%        bodyparts is a table. It may be empty when the tracking provider does
%        not expose body-part coordinates.
%
%   Outputs:
%       joinedStdTable - A joined table with centerpointData's N rows equal to either A or B, whichever is longer, with rows matched by 'Trial time' and/or 'Stimulus name' for the least amount of inserted missing rows. Centerpoint and, when present in both inputs, bodypart data columns are widened in A-then-B order. Optional fields absent from both inputs are omitted from the output. Other fields in the struct (like metadata) are either copied if both are the same (like stimuliSorted, fps, and px2cm), or merged in order of [A, B] if they are different (like animalMetadata or stimfileName).
%           For the intended use case, where B is a superset of A (i.e. B includes A plus some extra stimuli blocks somewhere in the trial, typically at the end), the resulting centerpointData and, when present, bodyparts tables will have the same number of rows as B, with rows from A matched to B by stimulus block and missing rows inserted where no match is found.
%       nAnimalsA - Number of animalMetadata entries contributed by stdTableA.
%           This is returned for compatibility and is also embedded in the
%           output when 'EmbeddedNAnimalA' is true.
%
%  See also: population.stats.populationPositionOverTime
%
%
% BACKGROUND and USE CASE:
% When creating stimuli using the playlist generator included in the NI-DAQmx Media Player (https://github.com/codynhanpham/nidaq_audioplayer)
% That is, create a YML-formatted playlist WITH A SET SEED, then generate the FLAC stimuli from that playlist
% all randomizations will be consistent in the same order as long as the same seed is used.
% For example, you created a playlist with seed 12345, repeating [track1.wav, pause[5000|10000]ms] 10 times then append [track2.wav] at the end to produce output1.flac
% Then, you create another playlist with the same seed 12345, repeating [track1.wav, pause[5000|10000]ms] 15 times then append [track2.wav] at the end to produce output2.flac
% The first 10 repetitions of output2.flac and output1.flac will be the same, even though pause[5000|10000]ms will generate a random pause duration each time between 5000ms and 10000ms.
% That is because the randomization is designed to be deterministic based on the seed. As long as the randomization action are performed in the same order, the same sequence will be generated.
%
% This function will greedily match the stimuli of 2 different standardizedTables.centerpointData (generated by population.stats.populationPositionOverTime) tables by their 'Trial time' and 'Stimulus name' columns from time 0s to the end of the trial, matching the stimuli in the order they appear, filling in missing values where no match is found.
% Refer back to the example above, this will match the first 10 stimuli of output2.flac to output1.flac, fill in NaNs for the remaining 5 stimuli of output2.flac that have no match in output1.flac, and continue to match the remaining matching stimuli by order.
%
% In short, think of this function similar to Git merging 2 files where one of them is a superset (with added rows) of the other file, and we want to align the rows of the superset file to the subset file by matching on 'Trial time' and 'Stimulus name'.
%
%
% WHY?
% During testing, sometimes we want to check the effect of different stimulus lengths on animal behavior.
% Some stimuli playlists contains shorter or longer versions of the same [stimuli+ISI] segment, only differing in the number of repetitions of those segments.
% This results in different number of stimuli per trial, thus different lengths of standardized center point tables.
% This function allows us to align those different length standardized center point tables by matching the stimuli based on 'Trial time' and 'Stimulus name', so that we can compare animal behavior across different stimulus lengths.
%
% Optional-field (20260818) notes:
%   - fps and px2cm are top-level scalar metadata and must agree between A and B.
%   - bodyparts is a direct table, not a nested bodyparts.data field.
%   - bodyparts are aligned with the same stimulus-block row mapping as centerpointData.
%   - Each optional field must be present in both inputs or absent from both.
%   - Optional fields absent from both inputs are ignored and omitted from the output.

function [joinedStdTable, nAnimalsA] = joinStdTableByStim(stdTableA, stdTableB, options)
    arguments
        stdTableA struct
        stdTableB struct
        options.EmbeddedNAnimalA (1,1) logical = false
    end

    validateInput(stdTableA, 'stdTableA');
    validateInput(stdTableB, 'stdTableB');

    optionalFields = {'fps', 'px2cm', 'bodyparts'};
    for fieldIndex = 1:numel(optionalFields)
        validateOptionalFieldPresence(stdTableA, stdTableB, optionalFields{fieldIndex});
    end

    if ~isequal(stdTableA.stimuliSorted, stdTableB.stimuliSorted)
        error('population:temp:joinStdTableByStim:StimuliMismatch', ...
            'The provided standardized tables must have the same stimuliSorted field.');
    end
    hasFPS = isfield(stdTableA, 'fps');
    if hasFPS && ~isequaln(stdTableA.fps, stdTableB.fps)
        error('population:temp:joinStdTableByStim:FPSMismatch', ...
            'The provided standardized tables must have the same fps.');
    end
    hasPx2cm = isfield(stdTableA, 'px2cm');
    if hasPx2cm && ~isequaln(stdTableA.px2cm, stdTableB.px2cm)
        error('population:temp:joinStdTableByStim:Px2cmMismatch', ...
            'The provided standardized tables must have the same px2cm.');
    end

    centerpointA = stdTableA.centerpointData;
    centerpointB = stdTableB.centerpointData;
    keyColumns = {'Trial time', 'Stimulus name'};
    centerpointColumns = setdiff(centerpointA.Properties.VariableNames, keyColumns, 'stable');
    centerpointColumnsB = setdiff(centerpointB.Properties.VariableNames, keyColumns, 'stable');
    if ~isequal(sort(centerpointColumns), sort(centerpointColumnsB))
        error('population:temp:joinStdTableByStim:CenterpointColumnsMismatch', ...
            ['The provided standardized tables must have the same centerpoint ', ...
            'data variables other than Trial time and Stimulus name.']);
    end

    [baseCenterpoint, mapA, mapB] = makeRowMaps(centerpointA, centerpointB);

    joinedStdTable = struct();
    joinedStdTable.stimfileName = {stdTableA.stimfileName; stdTableB.stimfileName};
    joinedStdTable.stimuliSorted = stdTableA.stimuliSorted;
    if hasFPS
        joinedStdTable.fps = stdTableA.fps;
    end
    if hasPx2cm
        joinedStdTable.px2cm = stdTableA.px2cm;
    end

    joinedStdTable.animalMetadata = stdTableA.animalMetadata;
    keysA = keys(stdTableA.animalMetadata);
    keysB = keys(stdTableB.animalMetadata);
    nAnimalsA = numel(keysA);
    if options.EmbeddedNAnimalA
        joinedStdTable.nAnimalsA = nAnimalsA;
    end
    if ~isempty(intersect(keysA, keysB))
        error('population:temp:joinStdTableByStim:MetadataKeyOverlap', ...
            'The provided standardized tables have overlapping animalMetadata keys.');
    end
    for keyIndex = 1:numel(keysB)
        key = keysB{keyIndex};
        joinedStdTable.animalMetadata(key) = stdTableB.animalMetadata(key);
    end

    joinedStdTable.centerpointData = joinDataTable(...
        centerpointA, centerpointB, baseCenterpoint, mapA, mapB, centerpointColumns);
    if isfield(stdTableA, 'bodyparts')
        joinedStdTable.bodyparts = joinBodypartTables(...
            stdTableA.bodyparts, stdTableB.bodyparts, baseCenterpoint, mapA, mapB);
    end
end

function validateInput(stdTable, inputName)
    requiredFields = {'stimfileName', 'stimuliSorted', 'animalMetadata', ...
        'centerpointData'};
    missingFields = setdiff(requiredFields, fieldnames(stdTable));
    if ~isempty(missingFields)
        error('population:temp:joinStdTableByStim:MissingFields', ...
            '%s is missing required fields: %s.', inputName, strjoin(missingFields, ', '));
    end
    if isfield(stdTable, 'fps')
        if ~isnumeric(stdTable.fps) || ~isscalar(stdTable.fps) || ...
                (~isfinite(stdTable.fps) && ~isnan(stdTable.fps))
            error('population:temp:joinStdTableByStim:InvalidFPS', ...
                '%s.fps must be a numeric scalar, finite or NaN.', inputName);
        end
    end
    if isfield(stdTable, 'px2cm')
        if ~isnumeric(stdTable.px2cm) || ~isscalar(stdTable.px2cm) || ...
                (~isfinite(stdTable.px2cm) && ~isnan(stdTable.px2cm))
            error('population:temp:joinStdTableByStim:InvalidPx2cm', ...
                '%s.px2cm must be a numeric scalar, finite or NaN.', inputName);
        end
    end
    if ~istable(stdTable.centerpointData) || ...
            (isfield(stdTable, 'bodyparts') && ~istable(stdTable.bodyparts))
        error('population:temp:joinStdTableByStim:InvalidTables', ...
            '%s.centerpointData must be a table and %s.bodyparts, when present, must be a table.', ...
            inputName, inputName);
    end
    try
        keys(stdTable.animalMetadata);
    catch ME
        error('population:temp:joinStdTableByStim:InvalidAnimalMetadata', ...
            '%s.animalMetadata must be a dictionary-like key/value object. %s', ...
            inputName, ME.message);
    end

    requiredCenterpointColumns = {'Trial time', 'Stimulus name', 'X center', ...
        'Y center', 'Distance from Midline', 'Arena Grid Score'};
    missingCenterpointColumns = setdiff(requiredCenterpointColumns, ...
        stdTable.centerpointData.Properties.VariableNames);
    if ~isempty(missingCenterpointColumns)
        error('population:temp:joinStdTableByStim:MissingCenterpointColumns', ...
            '%s.centerpointData is missing columns: %s.', inputName, ...
            strjoin(missingCenterpointColumns, ', '));
    end
    if isfield(stdTable, 'bodyparts') && ~isempty(stdTable.bodyparts)
        missingBodypartColumns = setdiff({'Trial time', 'Stimulus name'}, ...
            stdTable.bodyparts.Properties.VariableNames);
        if ~isempty(missingBodypartColumns)
            error('population:temp:joinStdTableByStim:MissingBodypartColumns', ...
                '%s.bodyparts is missing columns: %s.', inputName, ...
                strjoin(missingBodypartColumns, ', '));
        end
        if height(stdTable.bodyparts) ~= height(stdTable.centerpointData)
            error('population:temp:joinStdTableByStim:BodypartRowCountMismatch', ...
                '%s.bodyparts and %s.centerpointData must have the same number of rows.', ...
                inputName, inputName);
        end
    end
end

function validateOptionalFieldPresence(stdTableA, stdTableB, fieldName)
    if xor(isfield(stdTableA, fieldName), isfield(stdTableB, fieldName))
        error('population:temp:joinStdTableByStim:OptionalFieldPresenceMismatch', ...
            'The optional field %s must either exist in both standardized tables or be absent from both.', ...
            fieldName);
    end
end

function [baseTable, mapA, mapB] = makeRowMaps(tableA, tableB)
    dtA = unique(round(diff(tableA.('Trial time')), 10));
    dtB = unique(round(diff(tableB.('Trial time')), 10));
    if ~isequal(dtA, dtB)
        error('population:temp:joinStdTableByStim:SamplingRateMismatch', ...
            'The provided standardized tables must have the same sampling rate.');
    end

    isBaseA = height(tableA) >= height(tableB);
    if isBaseA
        baseTable = tableA;
        matchTable = tableB;
    else
        baseTable = tableB;
        matchTable = tableA;
    end

    baseBlocks = getStimBlocks(baseTable);
    matchBlocks = getStimBlocks(matchTable);
    matchRowMap = nan(height(baseTable), 1);
    matchBlockIndex = 1;
    for baseBlockIndex = 1:numel(baseBlocks)
        baseBlock = baseBlocks(baseBlockIndex);
        if matchBlockIndex > numel(matchBlocks)
            break;
        end
        matchBlock = matchBlocks(matchBlockIndex);
        if strcmp(baseBlock.Name, matchBlock.Name)
            nRows = min(baseBlock.Count, matchBlock.Count);
            baseRows = baseBlock.Start:(baseBlock.Start + nRows - 1);
            matchRows = matchBlock.Start:(matchBlock.Start + nRows - 1);
            matchRowMap(baseRows) = matchRows;
            matchBlockIndex = matchBlockIndex + 1;
        end
    end

    if isBaseA
        mapA = (1:height(tableA))';
        mapB = matchRowMap;
    else
        mapA = matchRowMap;
        mapB = (1:height(tableB))';
    end
end

function joinedTable = joinDataTable(tableA, tableB, baseTable, mapA, mapB, dataColumns)
    joinedTable = baseTable(:, {'Trial time', 'Stimulus name'});
    for columnIndex = 1:numel(dataColumns)
        columnName = dataColumns{columnIndex};
        alignedA = alignColumn(tableA.(columnName), mapA, height(baseTable));
        alignedB = alignColumn(tableB.(columnName), mapB, height(baseTable));
        joinedTable.(columnName) = [alignedA, alignedB];
    end
end

function joinedTable = joinBodypartTables(bodypartsA, bodypartsB, baseCenterpoint, mapA, mapB)
    if isempty(bodypartsA) && isempty(bodypartsB)
        joinedTable = table();
        return;
    end

    joinedTable = baseCenterpoint(:, {'Trial time', 'Stimulus name'});
    keyColumns = {'Trial time', 'Stimulus name'};
    columnsA = setdiff(bodypartsA.Properties.VariableNames, keyColumns, 'stable');
    columnsB = setdiff(bodypartsB.Properties.VariableNames, keyColumns, 'stable');
    dataColumns = unique([columnsA, columnsB], 'stable');

    for columnIndex = 1:numel(dataColumns)
        columnName = dataColumns{columnIndex};
        hasA = ismember(columnName, columnsA);
        hasB = ismember(columnName, columnsB);
        if hasA && hasB
            dataA = bodypartsA.(columnName);
            dataB = bodypartsB.(columnName);
            if ~strcmp(class(dataA), class(dataB))
                error('population:temp:joinStdTableByStim:BodypartColumnMismatch', ...
                    'Bodypart variable %s has incompatible data types.', columnName);
            end
            alignedA = alignColumn(dataA, mapA, height(baseCenterpoint));
            alignedB = alignColumn(dataB, mapB, height(baseCenterpoint));
        elseif hasA
            dataA = bodypartsA.(columnName);
            alignedA = alignColumn(dataA, mapA, height(baseCenterpoint));
            alignedB = emptyColumnLike(dataA, height(baseCenterpoint), 0);
        else
            dataB = bodypartsB.(columnName);
            alignedA = emptyColumnLike(dataB, height(baseCenterpoint), 0);
            alignedB = alignColumn(dataB, mapB, height(baseCenterpoint));
        end
        joinedTable.(columnName) = [alignedA, alignedB];
    end
end

function aligned = alignColumn(data, rowMap, nRows)
    aligned = emptyColumnLike(data, nRows, size(data, 2));
    validRows = ~isnan(rowMap);
    if any(validRows)
        aligned(validRows, :) = data(rowMap(validRows), :);
    end
end

function emptyColumn = emptyColumnLike(data, nRows, nColumns)
    if isnumeric(data)
        emptyColumn = NaN(nRows, nColumns, 'like', data);
    elseif islogical(data)
        emptyColumn = false(nRows, nColumns);
    elseif isstring(data)
        emptyColumn = strings(nRows, nColumns);
        emptyColumn(:) = missing;
    elseif iscategorical(data)
        emptyColumn = categorical(nan(nRows, nColumns));
    elseif iscell(data)
        emptyColumn = cell(nRows, nColumns);
        emptyColumn(:) = {missing};
    else
        error('population:temp:joinStdTableByStim:UnsupportedColumnType', ...
            'Unsupported table variable type: %s.', class(data));
    end
end

function blocks = getStimBlocks(T)
    stims = string(T.('Stimulus name'));
    if isempty(stims)
        blocks = struct('Name', {}, 'Start', {}, 'End', {}, 'Count', {});
        return;
    end
    isChange = [true; stims(1:end-1) ~= stims(2:end)];
    startIndex = find(isChange);
    endIndex = [startIndex(2:end)-1; numel(stims)];
    blocks = struct('Name', cellstr(stims(startIndex)), ...
        'Start', num2cell(startIndex), 'End', num2cell(endIndex), ...
        'Count', num2cell(endIndex - startIndex + 1));
end
